// Code generated by internal/genstrict; DO NOT EDIT.

package httpapi

import (
	"context"
	"net/http"

	"github.com/magedmg/RSP-website/backend/internal/generated"
)

func (strictAdapter) CloseSeason(ctx context.Context, _ generated.CloseSeasonRequestObject) (generated.CloseSeasonResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitCloseSeasonResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) CorrectMockInterviewIdentities(ctx context.Context, _ generated.CorrectMockInterviewIdentitiesRequestObject) (generated.CorrectMockInterviewIdentitiesResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitCorrectMockInterviewIdentitiesResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) CreateMentorship(ctx context.Context, _ generated.CreateMentorshipRequestObject) (generated.CreateMentorshipResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitCreateMentorshipResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) CreateMockInterview(ctx context.Context, _ generated.CreateMockInterviewRequestObject) (generated.CreateMockInterviewResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitCreateMockInterviewResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) CreateProblemAttempt(ctx context.Context, _ generated.CreateProblemAttemptRequestObject) (generated.CreateProblemAttemptResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitCreateProblemAttemptResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) CreateSeason(ctx context.Context, _ generated.CreateSeasonRequestObject) (generated.CreateSeasonResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitCreateSeasonResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) CreateSeasonMember(ctx context.Context, _ generated.CreateSeasonMemberRequestObject) (generated.CreateSeasonMemberResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitCreateSeasonMemberResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) CreateSeasonWeek(ctx context.Context, _ generated.CreateSeasonWeekRequestObject) (generated.CreateSeasonWeekResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitCreateSeasonWeekResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) DeleteMentorship(ctx context.Context, _ generated.DeleteMentorshipRequestObject) (generated.DeleteMentorshipResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitDeleteMentorshipResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) DeleteMockInterview(ctx context.Context, _ generated.DeleteMockInterviewRequestObject) (generated.DeleteMockInterviewResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitDeleteMockInterviewResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) DeleteProblemAttempt(ctx context.Context, _ generated.DeleteProblemAttemptRequestObject) (generated.DeleteProblemAttemptResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitDeleteProblemAttemptResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) DeleteSeasonWeek(ctx context.Context, _ generated.DeleteSeasonWeekRequestObject) (generated.DeleteSeasonWeekResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitDeleteSeasonWeekResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) DismissCurrentRecommendation(ctx context.Context, _ generated.DismissCurrentRecommendationRequestObject) (generated.DismissCurrentRecommendationResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitDismissCurrentRecommendationResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) EnableUserPracticeGoals(ctx context.Context, _ generated.EnableUserPracticeGoalsRequestObject) (generated.EnableUserPracticeGoalsResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitEnableUserPracticeGoalsResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) GetCurrentRecommendation(ctx context.Context, _ generated.GetCurrentRecommendationRequestObject) (generated.GetCurrentRecommendationResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitGetCurrentRecommendationResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) GetLiveness(ctx context.Context, _ generated.GetLivenessRequestObject) (generated.GetLivenessResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) GetMe(ctx context.Context, _ generated.GetMeRequestObject) (generated.GetMeResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) GetMetrics(ctx context.Context, _ generated.GetMetricsRequestObject) (generated.GetMetricsResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) GetOpenAPI(ctx context.Context, _ generated.GetOpenAPIRequestObject) (generated.GetOpenAPIResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitGetOpenAPIResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) GetPracticeSettings(ctx context.Context, _ generated.GetPracticeSettingsRequestObject) (generated.GetPracticeSettingsResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitGetPracticeSettingsResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) GetReadiness(ctx context.Context, _ generated.GetReadinessRequestObject) (generated.GetReadinessResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) GetSeason(ctx context.Context, _ generated.GetSeasonRequestObject) (generated.GetSeasonResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitGetSeasonResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) GetUser(ctx context.Context, _ generated.GetUserRequestObject) (generated.GetUserResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) GetUserPracticeSettings(ctx context.Context, _ generated.GetUserPracticeSettingsRequestObject) (generated.GetUserPracticeSettingsResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitGetUserPracticeSettingsResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) GrantAdminUserGlobalRole(ctx context.Context, _ generated.GrantAdminUserGlobalRoleRequestObject) (generated.GrantAdminUserGlobalRoleResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitGrantAdminUserGlobalRoleResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) ListAdminUserGlobalRoles(ctx context.Context, _ generated.ListAdminUserGlobalRolesRequestObject) (generated.ListAdminUserGlobalRolesResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitListAdminUserGlobalRolesResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) ListAdminUsers(ctx context.Context, _ generated.ListAdminUsersRequestObject) (generated.ListAdminUsersResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitListAdminUsersResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) ListEnrollmentCandidates(ctx context.Context, _ generated.ListEnrollmentCandidatesRequestObject) (generated.ListEnrollmentCandidatesResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitListEnrollmentCandidatesResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) ListLeetcodeProblems(ctx context.Context, _ generated.ListLeetcodeProblemsRequestObject) (generated.ListLeetcodeProblemsResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitListLeetcodeProblemsResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) ListMockInterviewParticipants(ctx context.Context, _ generated.ListMockInterviewParticipantsRequestObject) (generated.ListMockInterviewParticipantsResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitListMockInterviewParticipantsResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) ListMockInterviews(ctx context.Context, _ generated.ListMockInterviewsRequestObject) (generated.ListMockInterviewsResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitListMockInterviewsResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) ListProblemAttempts(ctx context.Context, _ generated.ListProblemAttemptsRequestObject) (generated.ListProblemAttemptsResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitListProblemAttemptsResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) ListSeasonMembers(ctx context.Context, _ generated.ListSeasonMembersRequestObject) (generated.ListSeasonMembersResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitListSeasonMembersResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) ListSeasonMentorships(ctx context.Context, _ generated.ListSeasonMentorshipsRequestObject) (generated.ListSeasonMentorshipsResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitListSeasonMentorshipsResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) ListSeasonWeeks(ctx context.Context, _ generated.ListSeasonWeeksRequestObject) (generated.ListSeasonWeeksResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitListSeasonWeeksResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) ListSeasons(ctx context.Context, _ generated.ListSeasonsRequestObject) (generated.ListSeasonsResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitListSeasonsResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) ListUsers(ctx context.Context, _ generated.ListUsersRequestObject) (generated.ListUsersResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitListUsersResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) PromoteSeasonMember(ctx context.Context, _ generated.PromoteSeasonMemberRequestObject) (generated.PromoteSeasonMemberResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitPromoteSeasonMemberResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) RemoveSeasonMember(ctx context.Context, _ generated.RemoveSeasonMemberRequestObject) (generated.RemoveSeasonMemberResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitRemoveSeasonMemberResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) ReopenSeason(ctx context.Context, _ generated.ReopenSeasonRequestObject) (generated.ReopenSeasonResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitReopenSeasonResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) RequestLeetcodeSync(ctx context.Context, _ generated.RequestLeetcodeSyncRequestObject) (generated.RequestLeetcodeSyncResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitRequestLeetcodeSyncResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) ReviewMockInterviewRound(ctx context.Context, _ generated.ReviewMockInterviewRoundRequestObject) (generated.ReviewMockInterviewRoundResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitReviewMockInterviewRoundResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) RevokeAdminUserGlobalRole(ctx context.Context, _ generated.RevokeAdminUserGlobalRoleRequestObject) (generated.RevokeAdminUserGlobalRoleResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitRevokeAdminUserGlobalRoleResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) SetAdminUserAccountState(ctx context.Context, _ generated.SetAdminUserAccountStateRequestObject) (generated.SetAdminUserAccountStateResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitSetAdminUserAccountStateResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) SuggestMeSlug(ctx context.Context, _ generated.SuggestMeSlugRequestObject) (generated.SuggestMeSlugResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitSuggestMeSlugResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) UpdateMe(ctx context.Context, _ generated.UpdateMeRequestObject) (generated.UpdateMeResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) UpdateMentorship(ctx context.Context, _ generated.UpdateMentorshipRequestObject) (generated.UpdateMentorshipResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitUpdateMentorshipResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) UpdateMockInterview(ctx context.Context, _ generated.UpdateMockInterviewRequestObject) (generated.UpdateMockInterviewResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitUpdateMockInterviewResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) UpdatePracticeSettings(ctx context.Context, _ generated.UpdatePracticeSettingsRequestObject) (generated.UpdatePracticeSettingsResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitUpdatePracticeSettingsResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) UpdateProblemAttempt(ctx context.Context, _ generated.UpdateProblemAttemptRequestObject) (generated.UpdateProblemAttemptResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitUpdateProblemAttemptResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) UpdateSeason(ctx context.Context, _ generated.UpdateSeasonRequestObject) (generated.UpdateSeasonResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitUpdateSeasonResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) UpdateSeasonMember(ctx context.Context, _ generated.UpdateSeasonMemberRequestObject) (generated.UpdateSeasonMemberResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitUpdateSeasonMemberResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) UpdateSeasonResources(ctx context.Context, _ generated.UpdateSeasonResourcesRequestObject) (generated.UpdateSeasonResourcesResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitUpdateSeasonResourcesResponse(w http.ResponseWriter) error {
	return response.write(w)
}

func (strictAdapter) UpdateSeasonWeek(ctx context.Context, _ generated.UpdateSeasonWeekRequestObject) (generated.UpdateSeasonWeekResponseObject, error) {
	return strictResponse(ctx)
}

func (response *strictManualResponse) VisitUpdateSeasonWeekResponse(w http.ResponseWriter) error {
	return response.write(w)
}
