// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEvent = `-- name: AppendAuditEvent :one
INSERT INTO app.audit_events (
  id, actor_user_id, action, subject_type, subject_id, request_id, ip_hash, data, occurred_at
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $9
)
RETURNING id, actor_user_id, action, subject_type, subject_id, request_id, ip_hash, data, occurred_at
`

type AppendAuditEventParams struct {
	ID          string             `db:"id" json:"id"`
	ActorUserID *string            `db:"actor_user_id" json:"actor_user_id"`
	Action      string             `db:"action" json:"action"`
	SubjectType string             `db:"subject_type" json:"subject_type"`
	SubjectID   string             `db:"subject_id" json:"subject_id"`
	RequestID   *string            `db:"request_id" json:"request_id"`
	IpHash      *string            `db:"ip_hash" json:"ip_hash"`
	Data        []byte             `db:"data" json:"data"`
	OccurredAt  pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AppAuditEvent, error) {
	row := q.db.QueryRow(ctx, appendAuditEvent,
		arg.ID,
		arg.ActorUserID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.RequestID,
		arg.IpHash,
		arg.Data,
		arg.OccurredAt,
	)
	var i AppAuditEvent
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.SubjectType,
		&i.SubjectID,
		&i.RequestID,
		&i.IpHash,
		&i.Data,
		&i.OccurredAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_user_id, action, subject_type, subject_id, request_id, ip_hash, data, occurred_at
FROM app.audit_events
WHERE ($1::text IS NULL OR subject_type = $1)
  AND ($2::text IS NULL OR subject_id = $2)
  AND ($3::text IS NULL OR actor_user_id = $3)
  AND ($4::text IS NULL OR (occurred_at, id) < ($5::timestamptz, $4::text))
ORDER BY occurred_at DESC, id DESC
LIMIT $6
`

type ListAuditEventsParams struct {
	SubjectType *string            `db:"subject_type" json:"subject_type"`
	SubjectID   *string            `db:"subject_id" json:"subject_id"`
	ActorUserID *string            `db:"actor_user_id" json:"actor_user_id"`
	AfterID     *string            `db:"after_id" json:"after_id"`
	AfterAt     pgtype.Timestamptz `db:"after_at" json:"after_at"`
	PageLimit   int32              `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AppAuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.SubjectType,
		arg.SubjectID,
		arg.ActorUserID,
		arg.AfterID,
		arg.AfterAt,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppAuditEvent{}
	for rows.Next() {
		var i AppAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.SubjectType,
			&i.SubjectID,
			&i.RequestID,
			&i.IpHash,
			&i.Data,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
