// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mentoring.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO app.enrollments (
  id, user_id, season_id, role, student_level
) VALUES (
  $1, $2, $3,
  $4, $5
)
RETURNING id, user_id, season_id, role, student_level, state, completed_by_close_id, state_changed_at, deleted_at, revision, created_at, updated_at, assignment_state, activated_at, close_assignment_state, close_activated_at
`

type CreateEnrollmentParams struct {
	ID           string          `db:"id" json:"id"`
	UserID       string          `db:"user_id" json:"user_id"`
	SeasonID     string          `db:"season_id" json:"season_id"`
	Role         AppSeasonRole   `db:"role" json:"role"`
	StudentLevel AppStudentLevel `db:"student_level" json:"student_level"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (AppEnrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment,
		arg.ID,
		arg.UserID,
		arg.SeasonID,
		arg.Role,
		arg.StudentLevel,
	)
	var i AppEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeasonID,
		&i.Role,
		&i.StudentLevel,
		&i.State,
		&i.CompletedByCloseID,
		&i.StateChangedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentState,
		&i.ActivatedAt,
		&i.CloseAssignmentState,
		&i.CloseActivatedAt,
	)
	return i, err
}

const createMentorship = `-- name: CreateMentorship :one
INSERT INTO app.mentorships (
  id, season_id, mentor_enrollment_id, student_enrollment_id
) VALUES (
  $1, $2, $3,
  $4
)
RETURNING id, season_id, mentor_enrollment_id, student_enrollment_id, ended_at, deleted_at, revision, created_at, updated_at
`

type CreateMentorshipParams struct {
	ID                  string `db:"id" json:"id"`
	SeasonID            string `db:"season_id" json:"season_id"`
	MentorEnrollmentID  string `db:"mentor_enrollment_id" json:"mentor_enrollment_id"`
	StudentEnrollmentID string `db:"student_enrollment_id" json:"student_enrollment_id"`
}

func (q *Queries) CreateMentorship(ctx context.Context, arg CreateMentorshipParams) (AppMentorship, error) {
	row := q.db.QueryRow(ctx, createMentorship,
		arg.ID,
		arg.SeasonID,
		arg.MentorEnrollmentID,
		arg.StudentEnrollmentID,
	)
	var i AppMentorship
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.MentorEnrollmentID,
		&i.StudentEnrollmentID,
		&i.EndedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endMentorship = `-- name: EndMentorship :one
UPDATE app.mentorships
SET ended_at = $1, revision = revision + 1
WHERE id = $2
  AND ended_at IS NULL
  AND revision = $3
  AND deleted_at IS NULL
RETURNING id, season_id, mentor_enrollment_id, student_enrollment_id, ended_at, deleted_at, revision, created_at, updated_at
`

type EndMentorshipParams struct {
	EndedAt  pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	ID       string             `db:"id" json:"id"`
	Revision int64              `db:"revision" json:"revision"`
}

func (q *Queries) EndMentorship(ctx context.Context, arg EndMentorshipParams) (AppMentorship, error) {
	row := q.db.QueryRow(ctx, endMentorship, arg.EndedAt, arg.ID, arg.Revision)
	var i AppMentorship
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.MentorEnrollmentID,
		&i.StudentEnrollmentID,
		&i.EndedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMentorshipsForSeason = `-- name: ListMentorshipsForSeason :many
SELECT m.id, m.season_id, m.mentor_enrollment_id, m.student_enrollment_id, m.ended_at, m.deleted_at, m.revision, m.created_at, m.updated_at,
       mentor_user.id AS mentor_user_id,
       mentor_user.display_name AS mentor_name,
       student_user.id AS student_user_id,
       student_user.display_name AS student_name
FROM app.mentorships AS m
JOIN app.enrollments AS mentor_enrollment ON mentor_enrollment.id = m.mentor_enrollment_id
JOIN app.users AS mentor_user ON mentor_user.id = mentor_enrollment.user_id
JOIN app.enrollments AS student_enrollment ON student_enrollment.id = m.student_enrollment_id
JOIN app.users AS student_user ON student_user.id = student_enrollment.user_id
WHERE m.season_id = $1 AND m.ended_at IS NULL AND m.deleted_at IS NULL
ORDER BY mentor_user.display_name, student_user.display_name, m.id
`

type ListMentorshipsForSeasonParams struct {
	SeasonID string `db:"season_id" json:"season_id"`
}

type ListMentorshipsForSeasonRow struct {
	ID                  string             `db:"id" json:"id"`
	SeasonID            string             `db:"season_id" json:"season_id"`
	MentorEnrollmentID  string             `db:"mentor_enrollment_id" json:"mentor_enrollment_id"`
	StudentEnrollmentID string             `db:"student_enrollment_id" json:"student_enrollment_id"`
	EndedAt             pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Revision            int64              `db:"revision" json:"revision"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	MentorUserID        string             `db:"mentor_user_id" json:"mentor_user_id"`
	MentorName          string             `db:"mentor_name" json:"mentor_name"`
	StudentUserID       string             `db:"student_user_id" json:"student_user_id"`
	StudentName         string             `db:"student_name" json:"student_name"`
}

func (q *Queries) ListMentorshipsForSeason(ctx context.Context, arg ListMentorshipsForSeasonParams) ([]ListMentorshipsForSeasonRow, error) {
	rows, err := q.db.Query(ctx, listMentorshipsForSeason, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMentorshipsForSeasonRow{}
	for rows.Next() {
		var i ListMentorshipsForSeasonRow
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.MentorEnrollmentID,
			&i.StudentEnrollmentID,
			&i.EndedAt,
			&i.DeletedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MentorUserID,
			&i.MentorName,
			&i.StudentUserID,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonEnrollments = `-- name: ListSeasonEnrollments :many
SELECT e.id, e.user_id, e.season_id, e.role, e.student_level, e.state, e.completed_by_close_id, e.state_changed_at, e.deleted_at, e.revision, e.created_at, e.updated_at, e.assignment_state, e.activated_at, e.close_assignment_state, e.close_activated_at, u.slug, u.display_name, u.avatar_url
FROM app.enrollments AS e
JOIN app.users AS u ON u.id = e.user_id
WHERE e.season_id = $1
  AND e.deleted_at IS NULL
  AND ($2::app.season_role IS NULL OR e.role = $2)
  AND ($3::app.enrollment_state IS NULL OR e.state = $3)
  AND ($4::text IS NULL OR (u.display_name, e.id) > ($5::text, $4::text))
ORDER BY u.display_name ASC, e.id ASC
LIMIT $6
`

type ListSeasonEnrollmentsParams struct {
	SeasonID  string                 `db:"season_id" json:"season_id"`
	Role      NullAppSeasonRole      `db:"role" json:"role"`
	State     NullAppEnrollmentState `db:"state" json:"state"`
	AfterID   *string                `db:"after_id" json:"after_id"`
	AfterName *string                `db:"after_name" json:"after_name"`
	PageLimit int32                  `db:"page_limit" json:"page_limit"`
}

type ListSeasonEnrollmentsRow struct {
	ID                   string                 `db:"id" json:"id"`
	UserID               string                 `db:"user_id" json:"user_id"`
	SeasonID             string                 `db:"season_id" json:"season_id"`
	Role                 AppSeasonRole          `db:"role" json:"role"`
	StudentLevel         AppStudentLevel        `db:"student_level" json:"student_level"`
	State                AppEnrollmentState     `db:"state" json:"state"`
	CompletedByCloseID   *string                `db:"completed_by_close_id" json:"completed_by_close_id"`
	StateChangedAt       pgtype.Timestamptz     `db:"state_changed_at" json:"state_changed_at"`
	DeletedAt            pgtype.Timestamptz     `db:"deleted_at" json:"deleted_at"`
	Revision             int64                  `db:"revision" json:"revision"`
	CreatedAt            pgtype.Timestamptz     `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz     `db:"updated_at" json:"updated_at"`
	AssignmentState      AppAssignmentState     `db:"assignment_state" json:"assignment_state"`
	ActivatedAt          pgtype.Timestamptz     `db:"activated_at" json:"activated_at"`
	CloseAssignmentState NullAppAssignmentState `db:"close_assignment_state" json:"close_assignment_state"`
	CloseActivatedAt     pgtype.Timestamptz     `db:"close_activated_at" json:"close_activated_at"`
	Slug                 string                 `db:"slug" json:"slug"`
	DisplayName          string                 `db:"display_name" json:"display_name"`
	AvatarUrl            *string                `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) ListSeasonEnrollments(ctx context.Context, arg ListSeasonEnrollmentsParams) ([]ListSeasonEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listSeasonEnrollments,
		arg.SeasonID,
		arg.Role,
		arg.State,
		arg.AfterID,
		arg.AfterName,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonEnrollmentsRow{}
	for rows.Next() {
		var i ListSeasonEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SeasonID,
			&i.Role,
			&i.StudentLevel,
			&i.State,
			&i.CompletedByCloseID,
			&i.StateChangedAt,
			&i.DeletedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignmentState,
			&i.ActivatedAt,
			&i.CloseAssignmentState,
			&i.CloseActivatedAt,
			&i.Slug,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteStudentLevel = `-- name: PromoteStudentLevel :one
UPDATE app.enrollments
SET student_level = $1, revision = revision + 1
WHERE id = $2
  AND role = 'student'
  AND state = 'active'
  AND revision = $3
  AND deleted_at IS NULL
RETURNING id, user_id, season_id, role, student_level, state, completed_by_close_id, state_changed_at, deleted_at, revision, created_at, updated_at, assignment_state, activated_at, close_assignment_state, close_activated_at
`

type PromoteStudentLevelParams struct {
	StudentLevel AppStudentLevel `db:"student_level" json:"student_level"`
	ID           string          `db:"id" json:"id"`
	Revision     int64           `db:"revision" json:"revision"`
}

func (q *Queries) PromoteStudentLevel(ctx context.Context, arg PromoteStudentLevelParams) (AppEnrollment, error) {
	row := q.db.QueryRow(ctx, promoteStudentLevel, arg.StudentLevel, arg.ID, arg.Revision)
	var i AppEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeasonID,
		&i.Role,
		&i.StudentLevel,
		&i.State,
		&i.CompletedByCloseID,
		&i.StateChangedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentState,
		&i.ActivatedAt,
		&i.CloseAssignmentState,
		&i.CloseActivatedAt,
	)
	return i, err
}

const recordEnrollmentRemoval = `-- name: RecordEnrollmentRemoval :one
INSERT INTO app.enrollment_removal_events (
  id, enrollment_id, season_id, subject_user_id, actor_user_id,
  resulting_state, reason, occurred_at
) VALUES (
  $1, $2, $3,
  $4, $5,
  $6, $7, $8
)
RETURNING id, enrollment_id, season_id, subject_user_id, actor_user_id, resulting_state, reason, occurred_at, deleted_at_legacy
`

type RecordEnrollmentRemovalParams struct {
	ID             string             `db:"id" json:"id"`
	EnrollmentID   string             `db:"enrollment_id" json:"enrollment_id"`
	SeasonID       string             `db:"season_id" json:"season_id"`
	SubjectUserID  string             `db:"subject_user_id" json:"subject_user_id"`
	ActorUserID    *string            `db:"actor_user_id" json:"actor_user_id"`
	ResultingState AppEnrollmentState `db:"resulting_state" json:"resulting_state"`
	Reason         string             `db:"reason" json:"reason"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) RecordEnrollmentRemoval(ctx context.Context, arg RecordEnrollmentRemovalParams) (AppEnrollmentRemovalEvent, error) {
	row := q.db.QueryRow(ctx, recordEnrollmentRemoval,
		arg.ID,
		arg.EnrollmentID,
		arg.SeasonID,
		arg.SubjectUserID,
		arg.ActorUserID,
		arg.ResultingState,
		arg.Reason,
		arg.OccurredAt,
	)
	var i AppEnrollmentRemovalEvent
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SeasonID,
		&i.SubjectUserID,
		&i.ActorUserID,
		&i.ResultingState,
		&i.Reason,
		&i.OccurredAt,
		&i.DeletedAtLegacy,
	)
	return i, err
}

const removeEnrollment = `-- name: RemoveEnrollment :one
UPDATE app.enrollments
SET state = $1,
    state_changed_at = $2,
    assignment_state = 'revoked',
    activated_at = NULL,
    revision = revision + 1
WHERE id = $3
  AND state = 'active'
  AND revision = $4
  AND deleted_at IS NULL
RETURNING id, user_id, season_id, role, student_level, state, completed_by_close_id, state_changed_at, deleted_at, revision, created_at, updated_at, assignment_state, activated_at, close_assignment_state, close_activated_at
`

type RemoveEnrollmentParams struct {
	ResultingState AppEnrollmentState `db:"resulting_state" json:"resulting_state"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ID             string             `db:"id" json:"id"`
	Revision       int64              `db:"revision" json:"revision"`
}

func (q *Queries) RemoveEnrollment(ctx context.Context, arg RemoveEnrollmentParams) (AppEnrollment, error) {
	row := q.db.QueryRow(ctx, removeEnrollment,
		arg.ResultingState,
		arg.OccurredAt,
		arg.ID,
		arg.Revision,
	)
	var i AppEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeasonID,
		&i.Role,
		&i.StudentLevel,
		&i.State,
		&i.CompletedByCloseID,
		&i.StateChangedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentState,
		&i.ActivatedAt,
		&i.CloseAssignmentState,
		&i.CloseActivatedAt,
	)
	return i, err
}
