// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: migration.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireLegacyMigrationLock = `-- name: AcquireLegacyMigrationLock :one
SELECT pg_advisory_xact_lock(593215744214775351::bigint)
`

func (q *Queries) AcquireLegacyMigrationLock(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, acquireLegacyMigrationLock)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}

const createMigrationRun = `-- name: CreateMigrationRun :one
INSERT INTO migration.runs (
  id, manifest_checksum, source_schema_fingerprint, source_snapshot_at, state
) VALUES (
  $1, $2, $3,
  $4, 'planned'
)
RETURNING id, manifest_checksum, source_schema_fingerprint, source_snapshot_at, state, started_at, finished_at, rolled_back_at, error_summary, created_at
`

type CreateMigrationRunParams struct {
	ID                      string             `db:"id" json:"id"`
	ManifestChecksum        string             `db:"manifest_checksum" json:"manifest_checksum"`
	SourceSchemaFingerprint string             `db:"source_schema_fingerprint" json:"source_schema_fingerprint"`
	SourceSnapshotAt        pgtype.Timestamptz `db:"source_snapshot_at" json:"source_snapshot_at"`
}

func (q *Queries) CreateMigrationRun(ctx context.Context, arg CreateMigrationRunParams) (MigrationRun, error) {
	row := q.db.QueryRow(ctx, createMigrationRun,
		arg.ID,
		arg.ManifestChecksum,
		arg.SourceSchemaFingerprint,
		arg.SourceSnapshotAt,
	)
	var i MigrationRun
	err := row.Scan(
		&i.ID,
		&i.ManifestChecksum,
		&i.SourceSchemaFingerprint,
		&i.SourceSnapshotAt,
		&i.State,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RolledBackAt,
		&i.ErrorSummary,
		&i.CreatedAt,
	)
	return i, err
}

const getMigrationRun = `-- name: GetMigrationRun :one
SELECT id, manifest_checksum, source_schema_fingerprint, source_snapshot_at, state, started_at, finished_at, rolled_back_at, error_summary, created_at FROM migration.runs WHERE id = $1
`

type GetMigrationRunParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) GetMigrationRun(ctx context.Context, arg GetMigrationRunParams) (MigrationRun, error) {
	row := q.db.QueryRow(ctx, getMigrationRun, arg.ID)
	var i MigrationRun
	err := row.Scan(
		&i.ID,
		&i.ManifestChecksum,
		&i.SourceSchemaFingerprint,
		&i.SourceSnapshotAt,
		&i.State,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RolledBackAt,
		&i.ErrorSummary,
		&i.CreatedAt,
	)
	return i, err
}

const listMigrationTableResults = `-- name: ListMigrationTableResults :many
SELECT run_id, source_table, source_count, imported_count, source_ids_checksum, transformed_checksum FROM migration.source_tables WHERE run_id = $1 ORDER BY source_table
`

type ListMigrationTableResultsParams struct {
	RunID string `db:"run_id" json:"run_id"`
}

func (q *Queries) ListMigrationTableResults(ctx context.Context, arg ListMigrationTableResultsParams) ([]MigrationSourceTable, error) {
	rows, err := q.db.Query(ctx, listMigrationTableResults, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MigrationSourceTable{}
	for rows.Next() {
		var i MigrationSourceTable
		if err := rows.Scan(
			&i.RunID,
			&i.SourceTable,
			&i.SourceCount,
			&i.ImportedCount,
			&i.SourceIdsChecksum,
			&i.TransformedChecksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMigrationApplied = `-- name: MarkMigrationApplied :one
UPDATE migration.runs
SET state = 'applied', finished_at = $1, error_summary = NULL
WHERE id = $2 AND state = 'applying'
RETURNING id, manifest_checksum, source_schema_fingerprint, source_snapshot_at, state, started_at, finished_at, rolled_back_at, error_summary, created_at
`

type MarkMigrationAppliedParams struct {
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	ID         string             `db:"id" json:"id"`
}

func (q *Queries) MarkMigrationApplied(ctx context.Context, arg MarkMigrationAppliedParams) (MigrationRun, error) {
	row := q.db.QueryRow(ctx, markMigrationApplied, arg.FinishedAt, arg.ID)
	var i MigrationRun
	err := row.Scan(
		&i.ID,
		&i.ManifestChecksum,
		&i.SourceSchemaFingerprint,
		&i.SourceSnapshotAt,
		&i.State,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RolledBackAt,
		&i.ErrorSummary,
		&i.CreatedAt,
	)
	return i, err
}

const markMigrationApplying = `-- name: MarkMigrationApplying :one
UPDATE migration.runs
SET state = 'applying', started_at = $1
WHERE id = $2 AND state = 'planned'
RETURNING id, manifest_checksum, source_schema_fingerprint, source_snapshot_at, state, started_at, finished_at, rolled_back_at, error_summary, created_at
`

type MarkMigrationApplyingParams struct {
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	ID        string             `db:"id" json:"id"`
}

func (q *Queries) MarkMigrationApplying(ctx context.Context, arg MarkMigrationApplyingParams) (MigrationRun, error) {
	row := q.db.QueryRow(ctx, markMigrationApplying, arg.StartedAt, arg.ID)
	var i MigrationRun
	err := row.Scan(
		&i.ID,
		&i.ManifestChecksum,
		&i.SourceSchemaFingerprint,
		&i.SourceSnapshotAt,
		&i.State,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RolledBackAt,
		&i.ErrorSummary,
		&i.CreatedAt,
	)
	return i, err
}

const markMigrationRolledBack = `-- name: MarkMigrationRolledBack :one
UPDATE migration.runs
SET state = 'rolled_back', rolled_back_at = $1
WHERE id = $2 AND state IN ('applied', 'verified')
RETURNING id, manifest_checksum, source_schema_fingerprint, source_snapshot_at, state, started_at, finished_at, rolled_back_at, error_summary, created_at
`

type MarkMigrationRolledBackParams struct {
	RolledBackAt pgtype.Timestamptz `db:"rolled_back_at" json:"rolled_back_at"`
	ID           string             `db:"id" json:"id"`
}

func (q *Queries) MarkMigrationRolledBack(ctx context.Context, arg MarkMigrationRolledBackParams) (MigrationRun, error) {
	row := q.db.QueryRow(ctx, markMigrationRolledBack, arg.RolledBackAt, arg.ID)
	var i MigrationRun
	err := row.Scan(
		&i.ID,
		&i.ManifestChecksum,
		&i.SourceSchemaFingerprint,
		&i.SourceSnapshotAt,
		&i.State,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RolledBackAt,
		&i.ErrorSummary,
		&i.CreatedAt,
	)
	return i, err
}

const markMigrationVerified = `-- name: MarkMigrationVerified :one
UPDATE migration.runs
SET state = 'verified', finished_at = $1
WHERE id = $2 AND state = 'applied'
RETURNING id, manifest_checksum, source_schema_fingerprint, source_snapshot_at, state, started_at, finished_at, rolled_back_at, error_summary, created_at
`

type MarkMigrationVerifiedParams struct {
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	ID         string             `db:"id" json:"id"`
}

func (q *Queries) MarkMigrationVerified(ctx context.Context, arg MarkMigrationVerifiedParams) (MigrationRun, error) {
	row := q.db.QueryRow(ctx, markMigrationVerified, arg.FinishedAt, arg.ID)
	var i MigrationRun
	err := row.Scan(
		&i.ID,
		&i.ManifestChecksum,
		&i.SourceSchemaFingerprint,
		&i.SourceSnapshotAt,
		&i.State,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RolledBackAt,
		&i.ErrorSummary,
		&i.CreatedAt,
	)
	return i, err
}

const recordRowProvenance = `-- name: RecordRowProvenance :exec
INSERT INTO migration.row_provenance (
  run_id, source_table, source_id, target_table, target_id,
  source_checksum, transformed_checksum, transformed_data, duplicate_group
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8,
  $9
)
`

type RecordRowProvenanceParams struct {
	RunID               string  `db:"run_id" json:"run_id"`
	SourceTable         string  `db:"source_table" json:"source_table"`
	SourceID            string  `db:"source_id" json:"source_id"`
	TargetTable         string  `db:"target_table" json:"target_table"`
	TargetID            string  `db:"target_id" json:"target_id"`
	SourceChecksum      string  `db:"source_checksum" json:"source_checksum"`
	TransformedChecksum string  `db:"transformed_checksum" json:"transformed_checksum"`
	TransformedData     []byte  `db:"transformed_data" json:"transformed_data"`
	DuplicateGroup      *string `db:"duplicate_group" json:"duplicate_group"`
}

func (q *Queries) RecordRowProvenance(ctx context.Context, arg RecordRowProvenanceParams) error {
	_, err := q.db.Exec(ctx, recordRowProvenance,
		arg.RunID,
		arg.SourceTable,
		arg.SourceID,
		arg.TargetTable,
		arg.TargetID,
		arg.SourceChecksum,
		arg.TransformedChecksum,
		arg.TransformedData,
		arg.DuplicateGroup,
	)
	return err
}

const recordSourceTable = `-- name: RecordSourceTable :exec
INSERT INTO migration.source_tables (
  run_id, source_table, source_count, imported_count,
  source_ids_checksum, transformed_checksum
) VALUES (
  $1, $2, $3,
  $4, $5,
  $6
)
`

type RecordSourceTableParams struct {
	RunID               string `db:"run_id" json:"run_id"`
	SourceTable         string `db:"source_table" json:"source_table"`
	SourceCount         int64  `db:"source_count" json:"source_count"`
	ImportedCount       int64  `db:"imported_count" json:"imported_count"`
	SourceIdsChecksum   string `db:"source_ids_checksum" json:"source_ids_checksum"`
	TransformedChecksum string `db:"transformed_checksum" json:"transformed_checksum"`
}

func (q *Queries) RecordSourceTable(ctx context.Context, arg RecordSourceTableParams) error {
	_, err := q.db.Exec(ctx, recordSourceTable,
		arg.RunID,
		arg.SourceTable,
		arg.SourceCount,
		arg.ImportedCount,
		arg.SourceIdsChecksum,
		arg.TransformedChecksum,
	)
	return err
}
