// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mock_interviews.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendMockInterviewVersion = `-- name: AppendMockInterviewVersion :one
INSERT INTO app.mock_interview_versions (
  id, mock_interview_id, version, actor_user_id, reason, snapshot
) VALUES (
  $1, $2, $3,
  $4, $5, $6
)
RETURNING id, mock_interview_id, version, actor_user_id, reason, snapshot, created_at
`

type AppendMockInterviewVersionParams struct {
	ID              string  `db:"id" json:"id"`
	MockInterviewID string  `db:"mock_interview_id" json:"mock_interview_id"`
	Version         int64   `db:"version" json:"version"`
	ActorUserID     *string `db:"actor_user_id" json:"actor_user_id"`
	Reason          string  `db:"reason" json:"reason"`
	Snapshot        []byte  `db:"snapshot" json:"snapshot"`
}

func (q *Queries) AppendMockInterviewVersion(ctx context.Context, arg AppendMockInterviewVersionParams) (AppMockInterviewVersion, error) {
	row := q.db.QueryRow(ctx, appendMockInterviewVersion,
		arg.ID,
		arg.MockInterviewID,
		arg.Version,
		arg.ActorUserID,
		arg.Reason,
		arg.Snapshot,
	)
	var i AppMockInterviewVersion
	err := row.Scan(
		&i.ID,
		&i.MockInterviewID,
		&i.Version,
		&i.ActorUserID,
		&i.Reason,
		&i.Snapshot,
		&i.CreatedAt,
	)
	return i, err
}

const createMockInterview = `-- name: CreateMockInterview :one
INSERT INTO app.mock_interviews (
  id, interviewer_user_id, interviewee_user_id, season_id, season_week_id,
  scheduled_at, duration_minutes, interviewer_notes_html
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8
)
RETURNING id, interviewer_user_id, interviewee_user_id, season_id, season_week_id, scheduled_at, duration_minutes, legacy_is_pass, interviewer_notes_html, notes_sanitization_changed, deleted_at, revision, created_at, updated_at
`

type CreateMockInterviewParams struct {
	ID                   string             `db:"id" json:"id"`
	InterviewerUserID    string             `db:"interviewer_user_id" json:"interviewer_user_id"`
	IntervieweeUserID    string             `db:"interviewee_user_id" json:"interviewee_user_id"`
	SeasonID             *string            `db:"season_id" json:"season_id"`
	SeasonWeekID         *string            `db:"season_week_id" json:"season_week_id"`
	ScheduledAt          pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	DurationMinutes      int32              `db:"duration_minutes" json:"duration_minutes"`
	InterviewerNotesHtml *string            `db:"interviewer_notes_html" json:"interviewer_notes_html"`
}

func (q *Queries) CreateMockInterview(ctx context.Context, arg CreateMockInterviewParams) (AppMockInterview, error) {
	row := q.db.QueryRow(ctx, createMockInterview,
		arg.ID,
		arg.InterviewerUserID,
		arg.IntervieweeUserID,
		arg.SeasonID,
		arg.SeasonWeekID,
		arg.ScheduledAt,
		arg.DurationMinutes,
		arg.InterviewerNotesHtml,
	)
	var i AppMockInterview
	err := row.Scan(
		&i.ID,
		&i.InterviewerUserID,
		&i.IntervieweeUserID,
		&i.SeasonID,
		&i.SeasonWeekID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.LegacyIsPass,
		&i.InterviewerNotesHtml,
		&i.NotesSanitizationChanged,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMockInterview = `-- name: GetMockInterview :one
SELECT id, interviewer_user_id, interviewee_user_id, season_id, season_week_id, scheduled_at, duration_minutes, legacy_is_pass, interviewer_notes_html, notes_sanitization_changed, deleted_at, revision, created_at, updated_at FROM app.mock_interviews WHERE id = $1 AND deleted_at IS NULL
`

type GetMockInterviewParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) GetMockInterview(ctx context.Context, arg GetMockInterviewParams) (AppMockInterview, error) {
	row := q.db.QueryRow(ctx, getMockInterview, arg.ID)
	var i AppMockInterview
	err := row.Scan(
		&i.ID,
		&i.InterviewerUserID,
		&i.IntervieweeUserID,
		&i.SeasonID,
		&i.SeasonWeekID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.LegacyIsPass,
		&i.InterviewerNotesHtml,
		&i.NotesSanitizationChanged,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMockInterviewRounds = `-- name: ListMockInterviewRounds :many
SELECT id, mock_interview_id, position, kind, review_status, interviewee_comment_html, review_sanitization_changed, reviewed_at, deleted_at, revision, created_at, updated_at FROM app.mock_interview_rounds
WHERE mock_interview_id = $1 AND deleted_at IS NULL
ORDER BY position, id
`

type ListMockInterviewRoundsParams struct {
	MockInterviewID string `db:"mock_interview_id" json:"mock_interview_id"`
}

func (q *Queries) ListMockInterviewRounds(ctx context.Context, arg ListMockInterviewRoundsParams) ([]AppMockInterviewRound, error) {
	rows, err := q.db.Query(ctx, listMockInterviewRounds, arg.MockInterviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppMockInterviewRound{}
	for rows.Next() {
		var i AppMockInterviewRound
		if err := rows.Scan(
			&i.ID,
			&i.MockInterviewID,
			&i.Position,
			&i.Kind,
			&i.ReviewStatus,
			&i.IntervieweeCommentHtml,
			&i.ReviewSanitizationChanged,
			&i.ReviewedAt,
			&i.DeletedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMockInterviewsForParticipant = `-- name: ListMockInterviewsForParticipant :many
SELECT mi.id, mi.interviewer_user_id, mi.interviewee_user_id, mi.season_id, mi.season_week_id, mi.scheduled_at, mi.duration_minutes, mi.legacy_is_pass, mi.interviewer_notes_html, mi.notes_sanitization_changed, mi.deleted_at, mi.revision, mi.created_at, mi.updated_at,
       interviewer.slug AS interviewer_slug,
       interviewer.display_name AS interviewer_name,
       interviewee.slug AS interviewee_slug,
       interviewee.display_name AS interviewee_name
FROM app.mock_interviews AS mi
JOIN app.users AS interviewer ON interviewer.id = mi.interviewer_user_id
JOIN app.users AS interviewee ON interviewee.id = mi.interviewee_user_id
WHERE mi.deleted_at IS NULL
  AND (
    $1::text = 'all'
    OR ($1::text = 'given' AND mi.interviewer_user_id = $2)
    OR ($1::text = 'received' AND mi.interviewee_user_id = $2)
  )
  AND ($3::text IS NULL OR (mi.scheduled_at, mi.id) < ($4::timestamptz, $3::text))
ORDER BY mi.scheduled_at DESC, mi.id DESC
LIMIT $5
`

type ListMockInterviewsForParticipantParams struct {
	Mode      string             `db:"mode" json:"mode"`
	UserID    string             `db:"user_id" json:"user_id"`
	AfterID   *string            `db:"after_id" json:"after_id"`
	AfterAt   pgtype.Timestamptz `db:"after_at" json:"after_at"`
	PageLimit int32              `db:"page_limit" json:"page_limit"`
}

type ListMockInterviewsForParticipantRow struct {
	ID                       string             `db:"id" json:"id"`
	InterviewerUserID        string             `db:"interviewer_user_id" json:"interviewer_user_id"`
	IntervieweeUserID        string             `db:"interviewee_user_id" json:"interviewee_user_id"`
	SeasonID                 *string            `db:"season_id" json:"season_id"`
	SeasonWeekID             *string            `db:"season_week_id" json:"season_week_id"`
	ScheduledAt              pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	DurationMinutes          int32              `db:"duration_minutes" json:"duration_minutes"`
	LegacyIsPass             *bool              `db:"legacy_is_pass" json:"legacy_is_pass"`
	InterviewerNotesHtml     *string            `db:"interviewer_notes_html" json:"interviewer_notes_html"`
	NotesSanitizationChanged bool               `db:"notes_sanitization_changed" json:"notes_sanitization_changed"`
	DeletedAt                pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Revision                 int64              `db:"revision" json:"revision"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	InterviewerSlug          string             `db:"interviewer_slug" json:"interviewer_slug"`
	InterviewerName          string             `db:"interviewer_name" json:"interviewer_name"`
	IntervieweeSlug          string             `db:"interviewee_slug" json:"interviewee_slug"`
	IntervieweeName          string             `db:"interviewee_name" json:"interviewee_name"`
}

func (q *Queries) ListMockInterviewsForParticipant(ctx context.Context, arg ListMockInterviewsForParticipantParams) ([]ListMockInterviewsForParticipantRow, error) {
	rows, err := q.db.Query(ctx, listMockInterviewsForParticipant,
		arg.Mode,
		arg.UserID,
		arg.AfterID,
		arg.AfterAt,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMockInterviewsForParticipantRow{}
	for rows.Next() {
		var i ListMockInterviewsForParticipantRow
		if err := rows.Scan(
			&i.ID,
			&i.InterviewerUserID,
			&i.IntervieweeUserID,
			&i.SeasonID,
			&i.SeasonWeekID,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.LegacyIsPass,
			&i.InterviewerNotesHtml,
			&i.NotesSanitizationChanged,
			&i.DeletedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InterviewerSlug,
			&i.InterviewerName,
			&i.IntervieweeSlug,
			&i.IntervieweeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMockInterview = `-- name: SoftDeleteMockInterview :one
UPDATE app.mock_interviews
SET deleted_at = $1, revision = revision + 1
WHERE id = $2
  AND interviewer_user_id = $3
  AND revision = $4
  AND deleted_at IS NULL
RETURNING revision
`

type SoftDeleteMockInterviewParams struct {
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	ID          string             `db:"id" json:"id"`
	ActorUserID string             `db:"actor_user_id" json:"actor_user_id"`
	Revision    int64              `db:"revision" json:"revision"`
}

func (q *Queries) SoftDeleteMockInterview(ctx context.Context, arg SoftDeleteMockInterviewParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteMockInterview,
		arg.DeletedAt,
		arg.ID,
		arg.ActorUserID,
		arg.Revision,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const updateMockInterview = `-- name: UpdateMockInterview :one
UPDATE app.mock_interviews
SET scheduled_at = $1,
    duration_minutes = $2,
    interviewer_notes_html = $3,
    revision = revision + 1
WHERE id = $4
  AND interviewer_user_id = $5
  AND revision = $6
  AND deleted_at IS NULL
RETURNING id, interviewer_user_id, interviewee_user_id, season_id, season_week_id, scheduled_at, duration_minutes, legacy_is_pass, interviewer_notes_html, notes_sanitization_changed, deleted_at, revision, created_at, updated_at
`

type UpdateMockInterviewParams struct {
	ScheduledAt          pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	DurationMinutes      int32              `db:"duration_minutes" json:"duration_minutes"`
	InterviewerNotesHtml *string            `db:"interviewer_notes_html" json:"interviewer_notes_html"`
	ID                   string             `db:"id" json:"id"`
	ActorUserID          string             `db:"actor_user_id" json:"actor_user_id"`
	Revision             int64              `db:"revision" json:"revision"`
}

func (q *Queries) UpdateMockInterview(ctx context.Context, arg UpdateMockInterviewParams) (AppMockInterview, error) {
	row := q.db.QueryRow(ctx, updateMockInterview,
		arg.ScheduledAt,
		arg.DurationMinutes,
		arg.InterviewerNotesHtml,
		arg.ID,
		arg.ActorUserID,
		arg.Revision,
	)
	var i AppMockInterview
	err := row.Scan(
		&i.ID,
		&i.InterviewerUserID,
		&i.IntervieweeUserID,
		&i.SeasonID,
		&i.SeasonWeekID,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.LegacyIsPass,
		&i.InterviewerNotesHtml,
		&i.NotesSanitizationChanged,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRoundReview = `-- name: UpdateRoundReview :one
UPDATE app.mock_interview_rounds AS r
SET review_status = $1,
    interviewee_comment_html = $2,
    reviewed_at = $3,
    revision = r.revision + 1
FROM app.mock_interviews AS mi
WHERE r.id = $4
  AND mi.id = r.mock_interview_id
  AND mi.interviewee_user_id = $5
  AND r.revision = $6
  AND r.deleted_at IS NULL
RETURNING r.id, r.mock_interview_id, r.position, r.kind, r.review_status, r.interviewee_comment_html, r.review_sanitization_changed, r.reviewed_at, r.deleted_at, r.revision, r.created_at, r.updated_at
`

type UpdateRoundReviewParams struct {
	ReviewStatus           AppReviewStatus    `db:"review_status" json:"review_status"`
	IntervieweeCommentHtml *string            `db:"interviewee_comment_html" json:"interviewee_comment_html"`
	ReviewedAt             pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	RoundID                string             `db:"round_id" json:"round_id"`
	ActorUserID            string             `db:"actor_user_id" json:"actor_user_id"`
	Revision               int64              `db:"revision" json:"revision"`
}

func (q *Queries) UpdateRoundReview(ctx context.Context, arg UpdateRoundReviewParams) (AppMockInterviewRound, error) {
	row := q.db.QueryRow(ctx, updateRoundReview,
		arg.ReviewStatus,
		arg.IntervieweeCommentHtml,
		arg.ReviewedAt,
		arg.RoundID,
		arg.ActorUserID,
		arg.Revision,
	)
	var i AppMockInterviewRound
	err := row.Scan(
		&i.ID,
		&i.MockInterviewID,
		&i.Position,
		&i.Kind,
		&i.ReviewStatus,
		&i.IntervieweeCommentHtml,
		&i.ReviewSanitizationChanged,
		&i.ReviewedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
