// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppAccountState string

const (
	AppAccountStateActive          AppAccountState = "active"
	AppAccountStateSuspended       AppAccountState = "suspended"
	AppAccountStateDeletionPending AppAccountState = "deletion_pending"
	AppAccountStateDeleted         AppAccountState = "deleted"
)

func (e *AppAccountState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppAccountState(s)
	case string:
		*e = AppAccountState(s)
	default:
		return fmt.Errorf("unsupported scan type for AppAccountState: %T", src)
	}
	return nil
}

type NullAppAccountState struct {
	AppAccountState AppAccountState `json:"app_account_state"`
	Valid           bool            `json:"valid"` // Valid is true if AppAccountState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppAccountState) Scan(value interface{}) error {
	if value == nil {
		ns.AppAccountState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppAccountState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppAccountState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppAccountState), nil
}

type AppAssignmentState string

const (
	AppAssignmentStatePendingMfa AppAssignmentState = "pending_mfa"
	AppAssignmentStateActive     AppAssignmentState = "active"
	AppAssignmentStateRevoked    AppAssignmentState = "revoked"
)

func (e *AppAssignmentState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppAssignmentState(s)
	case string:
		*e = AppAssignmentState(s)
	default:
		return fmt.Errorf("unsupported scan type for AppAssignmentState: %T", src)
	}
	return nil
}

type NullAppAssignmentState struct {
	AppAssignmentState AppAssignmentState `json:"app_assignment_state"`
	Valid              bool               `json:"valid"` // Valid is true if AppAssignmentState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppAssignmentState) Scan(value interface{}) error {
	if value == nil {
		ns.AppAssignmentState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppAssignmentState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppAssignmentState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppAssignmentState), nil
}

type AppAttemptOutcome string

const (
	AppAttemptOutcomeIndependentlySolved AppAttemptOutcome = "independently_solved"
	AppAttemptOutcomeSolvedWithHints     AppAttemptOutcome = "solved_with_hints"
	AppAttemptOutcomeNotSolved           AppAttemptOutcome = "not_solved"
	AppAttemptOutcomeUnknown             AppAttemptOutcome = "unknown"
)

func (e *AppAttemptOutcome) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppAttemptOutcome(s)
	case string:
		*e = AppAttemptOutcome(s)
	default:
		return fmt.Errorf("unsupported scan type for AppAttemptOutcome: %T", src)
	}
	return nil
}

type NullAppAttemptOutcome struct {
	AppAttemptOutcome AppAttemptOutcome `json:"app_attempt_outcome"`
	Valid             bool              `json:"valid"` // Valid is true if AppAttemptOutcome is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppAttemptOutcome) Scan(value interface{}) error {
	if value == nil {
		ns.AppAttemptOutcome, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppAttemptOutcome.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppAttemptOutcome) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppAttemptOutcome), nil
}

type AppEnrollmentState string

const (
	AppEnrollmentStateActive    AppEnrollmentState = "active"
	AppEnrollmentStateCompleted AppEnrollmentState = "completed"
	AppEnrollmentStateKicked    AppEnrollmentState = "kicked"
	AppEnrollmentStateWithdrawn AppEnrollmentState = "withdrawn"
)

func (e *AppEnrollmentState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppEnrollmentState(s)
	case string:
		*e = AppEnrollmentState(s)
	default:
		return fmt.Errorf("unsupported scan type for AppEnrollmentState: %T", src)
	}
	return nil
}

type NullAppEnrollmentState struct {
	AppEnrollmentState AppEnrollmentState `json:"app_enrollment_state"`
	Valid              bool               `json:"valid"` // Valid is true if AppEnrollmentState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppEnrollmentState) Scan(value interface{}) error {
	if value == nil {
		ns.AppEnrollmentState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppEnrollmentState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppEnrollmentState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppEnrollmentState), nil
}

type AppGlobalRole string

const (
	AppGlobalRoleDirector    AppGlobalRole = "director"
	AppGlobalRoleSystemAdmin AppGlobalRole = "system_admin"
)

func (e *AppGlobalRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppGlobalRole(s)
	case string:
		*e = AppGlobalRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AppGlobalRole: %T", src)
	}
	return nil
}

type NullAppGlobalRole struct {
	AppGlobalRole AppGlobalRole `json:"app_global_role"`
	Valid         bool          `json:"valid"` // Valid is true if AppGlobalRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppGlobalRole) Scan(value interface{}) error {
	if value == nil {
		ns.AppGlobalRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppGlobalRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppGlobalRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppGlobalRole), nil
}

type AppMigrationRunState string

const (
	AppMigrationRunStatePlanned    AppMigrationRunState = "planned"
	AppMigrationRunStateApplying   AppMigrationRunState = "applying"
	AppMigrationRunStateApplied    AppMigrationRunState = "applied"
	AppMigrationRunStateVerified   AppMigrationRunState = "verified"
	AppMigrationRunStateRolledBack AppMigrationRunState = "rolled_back"
	AppMigrationRunStateFailed     AppMigrationRunState = "failed"
)

func (e *AppMigrationRunState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppMigrationRunState(s)
	case string:
		*e = AppMigrationRunState(s)
	default:
		return fmt.Errorf("unsupported scan type for AppMigrationRunState: %T", src)
	}
	return nil
}

type NullAppMigrationRunState struct {
	AppMigrationRunState AppMigrationRunState `json:"app_migration_run_state"`
	Valid                bool                 `json:"valid"` // Valid is true if AppMigrationRunState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppMigrationRunState) Scan(value interface{}) error {
	if value == nil {
		ns.AppMigrationRunState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppMigrationRunState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppMigrationRunState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppMigrationRunState), nil
}

type AppMockRoundKind string

const (
	AppMockRoundKindBehavioural AppMockRoundKind = "behavioural"
	AppMockRoundKindLeetcode    AppMockRoundKind = "leetcode"
	AppMockRoundKindCustom      AppMockRoundKind = "custom"
)

func (e *AppMockRoundKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppMockRoundKind(s)
	case string:
		*e = AppMockRoundKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AppMockRoundKind: %T", src)
	}
	return nil
}

type NullAppMockRoundKind struct {
	AppMockRoundKind AppMockRoundKind `json:"app_mock_round_kind"`
	Valid            bool             `json:"valid"` // Valid is true if AppMockRoundKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppMockRoundKind) Scan(value interface{}) error {
	if value == nil {
		ns.AppMockRoundKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppMockRoundKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppMockRoundKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppMockRoundKind), nil
}

type AppProblemDifficulty string

const (
	AppProblemDifficultyEasy   AppProblemDifficulty = "easy"
	AppProblemDifficultyMedium AppProblemDifficulty = "medium"
	AppProblemDifficultyHard   AppProblemDifficulty = "hard"
)

func (e *AppProblemDifficulty) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppProblemDifficulty(s)
	case string:
		*e = AppProblemDifficulty(s)
	default:
		return fmt.Errorf("unsupported scan type for AppProblemDifficulty: %T", src)
	}
	return nil
}

type NullAppProblemDifficulty struct {
	AppProblemDifficulty AppProblemDifficulty `json:"app_problem_difficulty"`
	Valid                bool                 `json:"valid"` // Valid is true if AppProblemDifficulty is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppProblemDifficulty) Scan(value interface{}) error {
	if value == nil {
		ns.AppProblemDifficulty, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppProblemDifficulty.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppProblemDifficulty) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppProblemDifficulty), nil
}

type AppRecommendationState string

const (
	AppRecommendationStateActive     AppRecommendationState = "active"
	AppRecommendationStateAttempted  AppRecommendationState = "attempted"
	AppRecommendationStateDismissed  AppRecommendationState = "dismissed"
	AppRecommendationStateSuperseded AppRecommendationState = "superseded"
)

func (e *AppRecommendationState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppRecommendationState(s)
	case string:
		*e = AppRecommendationState(s)
	default:
		return fmt.Errorf("unsupported scan type for AppRecommendationState: %T", src)
	}
	return nil
}

type NullAppRecommendationState struct {
	AppRecommendationState AppRecommendationState `json:"app_recommendation_state"`
	Valid                  bool                   `json:"valid"` // Valid is true if AppRecommendationState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppRecommendationState) Scan(value interface{}) error {
	if value == nil {
		ns.AppRecommendationState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppRecommendationState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppRecommendationState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppRecommendationState), nil
}

type AppReviewStatus string

const (
	AppReviewStatusPending  AppReviewStatus = "pending"
	AppReviewStatusReviewed AppReviewStatus = "reviewed"
)

func (e *AppReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppReviewStatus(s)
	case string:
		*e = AppReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppReviewStatus: %T", src)
	}
	return nil
}

type NullAppReviewStatus struct {
	AppReviewStatus AppReviewStatus `json:"app_review_status"`
	Valid           bool            `json:"valid"` // Valid is true if AppReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppReviewStatus), nil
}

type AppSeasonRole string

const (
	AppSeasonRoleStudent     AppSeasonRole = "student"
	AppSeasonRoleMentor      AppSeasonRole = "mentor"
	AppSeasonRoleCoordinator AppSeasonRole = "coordinator"
)

func (e *AppSeasonRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppSeasonRole(s)
	case string:
		*e = AppSeasonRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AppSeasonRole: %T", src)
	}
	return nil
}

type NullAppSeasonRole struct {
	AppSeasonRole AppSeasonRole `json:"app_season_role"`
	Valid         bool          `json:"valid"` // Valid is true if AppSeasonRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppSeasonRole) Scan(value interface{}) error {
	if value == nil {
		ns.AppSeasonRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppSeasonRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppSeasonRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppSeasonRole), nil
}

type AppSeasonStatus string

const (
	AppSeasonStatusOpen   AppSeasonStatus = "open"
	AppSeasonStatusClosed AppSeasonStatus = "closed"
)

func (e *AppSeasonStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppSeasonStatus(s)
	case string:
		*e = AppSeasonStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppSeasonStatus: %T", src)
	}
	return nil
}

type NullAppSeasonStatus struct {
	AppSeasonStatus AppSeasonStatus `json:"app_season_status"`
	Valid           bool            `json:"valid"` // Valid is true if AppSeasonStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppSeasonStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppSeasonStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppSeasonStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppSeasonStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppSeasonStatus), nil
}

type AppStudentLevel string

const (
	AppStudentLevelNotApplicable AppStudentLevel = "not_applicable"
	AppStudentLevelNovice        AppStudentLevel = "novice"
	AppStudentLevelBeginner      AppStudentLevel = "beginner"
	AppStudentLevelIntermediate  AppStudentLevel = "intermediate"
	AppStudentLevelAdvanced      AppStudentLevel = "advanced"
)

func (e *AppStudentLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppStudentLevel(s)
	case string:
		*e = AppStudentLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for AppStudentLevel: %T", src)
	}
	return nil
}

type NullAppStudentLevel struct {
	AppStudentLevel AppStudentLevel `json:"app_student_level"`
	Valid           bool            `json:"valid"` // Valid is true if AppStudentLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppStudentLevel) Scan(value interface{}) error {
	if value == nil {
		ns.AppStudentLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppStudentLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppStudentLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppStudentLevel), nil
}

type MigrationAnomalySeverity string

const (
	MigrationAnomalySeverityWarning  MigrationAnomalySeverity = "warning"
	MigrationAnomalySeverityBlocking MigrationAnomalySeverity = "blocking"
)

func (e *MigrationAnomalySeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MigrationAnomalySeverity(s)
	case string:
		*e = MigrationAnomalySeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for MigrationAnomalySeverity: %T", src)
	}
	return nil
}

type NullMigrationAnomalySeverity struct {
	MigrationAnomalySeverity MigrationAnomalySeverity `json:"migration_anomaly_severity"`
	Valid                    bool                     `json:"valid"` // Valid is true if MigrationAnomalySeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMigrationAnomalySeverity) Scan(value interface{}) error {
	if value == nil {
		ns.MigrationAnomalySeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MigrationAnomalySeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMigrationAnomalySeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MigrationAnomalySeverity), nil
}

type MigrationResolutionAction string

const (
	MigrationResolutionActionMapID            MigrationResolutionAction = "map_id"
	MigrationResolutionActionUseValue         MigrationResolutionAction = "use_value"
	MigrationResolutionActionSkipSourceRow    MigrationResolutionAction = "skip_source_row"
	MigrationResolutionActionApproveTransform MigrationResolutionAction = "approve_transform"
)

func (e *MigrationResolutionAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MigrationResolutionAction(s)
	case string:
		*e = MigrationResolutionAction(s)
	default:
		return fmt.Errorf("unsupported scan type for MigrationResolutionAction: %T", src)
	}
	return nil
}

type NullMigrationResolutionAction struct {
	MigrationResolutionAction MigrationResolutionAction `json:"migration_resolution_action"`
	Valid                     bool                      `json:"valid"` // Valid is true if MigrationResolutionAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMigrationResolutionAction) Scan(value interface{}) error {
	if value == nil {
		ns.MigrationResolutionAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MigrationResolutionAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMigrationResolutionAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MigrationResolutionAction), nil
}

type AppAccountDeletionRequest struct {
	ID                string             `db:"id" json:"id"`
	UserID            string             `db:"user_id" json:"user_id"`
	RecoveryTokenHash string             `db:"recovery_token_hash" json:"recovery_token_hash"`
	RequestedAt       pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CancelledAt       pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	CompletedAt       pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type AppAuditEvent struct {
	ID          string             `db:"id" json:"id"`
	ActorUserID *string            `db:"actor_user_id" json:"actor_user_id"`
	Action      string             `db:"action" json:"action"`
	SubjectType string             `db:"subject_type" json:"subject_type"`
	SubjectID   string             `db:"subject_id" json:"subject_id"`
	RequestID   *string            `db:"request_id" json:"request_id"`
	IpHash      *string            `db:"ip_hash" json:"ip_hash"`
	Data        []byte             `db:"data" json:"data"`
	OccurredAt  pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

type AppBehaviouralMockInterviewRound struct {
	ID                   string             `db:"id" json:"id"`
	MockInterviewRoundID string             `db:"mock_interview_round_id" json:"mock_interview_round_id"`
	BehaviouralScore     int16              `db:"behavioural_score" json:"behavioural_score"`
	DeletedAt            pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppCustomMockInterviewRound struct {
	ID                         string             `db:"id" json:"id"`
	MockInterviewRoundID       string             `db:"mock_interview_round_id" json:"mock_interview_round_id"`
	ContentHtml                *string            `db:"content_html" json:"content_html"`
	Url                        *string            `db:"url" json:"url"`
	Score                      int16              `db:"score" json:"score"`
	ContentSanitizationChanged bool               `db:"content_sanitization_changed" json:"content_sanitization_changed"`
	DeletedAt                  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppCustomProblem struct {
	ID              string             `db:"id" json:"id"`
	ProblemID       string             `db:"problem_id" json:"problem_id"`
	DifficultyLabel string             `db:"difficulty_label" json:"difficulty_label"`
	QuestionHtml    string             `db:"question_html" json:"question_html"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Revision        int64              `db:"revision" json:"revision"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppEnrollment struct {
	ID                   string                 `db:"id" json:"id"`
	UserID               string                 `db:"user_id" json:"user_id"`
	SeasonID             string                 `db:"season_id" json:"season_id"`
	Role                 AppSeasonRole          `db:"role" json:"role"`
	StudentLevel         AppStudentLevel        `db:"student_level" json:"student_level"`
	State                AppEnrollmentState     `db:"state" json:"state"`
	CompletedByCloseID   *string                `db:"completed_by_close_id" json:"completed_by_close_id"`
	StateChangedAt       pgtype.Timestamptz     `db:"state_changed_at" json:"state_changed_at"`
	DeletedAt            pgtype.Timestamptz     `db:"deleted_at" json:"deleted_at"`
	Revision             int64                  `db:"revision" json:"revision"`
	CreatedAt            pgtype.Timestamptz     `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz     `db:"updated_at" json:"updated_at"`
	AssignmentState      AppAssignmentState     `db:"assignment_state" json:"assignment_state"`
	ActivatedAt          pgtype.Timestamptz     `db:"activated_at" json:"activated_at"`
	CloseAssignmentState NullAppAssignmentState `db:"close_assignment_state" json:"close_assignment_state"`
	CloseActivatedAt     pgtype.Timestamptz     `db:"close_activated_at" json:"close_activated_at"`
}

type AppEnrollmentRemovalEvent struct {
	ID              string             `db:"id" json:"id"`
	EnrollmentID    string             `db:"enrollment_id" json:"enrollment_id"`
	SeasonID        string             `db:"season_id" json:"season_id"`
	SubjectUserID   string             `db:"subject_user_id" json:"subject_user_id"`
	ActorUserID     *string            `db:"actor_user_id" json:"actor_user_id"`
	ResultingState  AppEnrollmentState `db:"resulting_state" json:"resulting_state"`
	Reason          string             `db:"reason" json:"reason"`
	OccurredAt      pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	DeletedAtLegacy pgtype.Timestamptz `db:"deleted_at_legacy" json:"deleted_at_legacy"`
}

type AppGlobalRoleAssignment struct {
	ID              string             `db:"id" json:"id"`
	UserID          string             `db:"user_id" json:"user_id"`
	Role            AppGlobalRole      `db:"role" json:"role"`
	State           AppAssignmentState `db:"state" json:"state"`
	GrantedByUserID *string            `db:"granted_by_user_id" json:"granted_by_user_id"`
	GrantedAt       pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	ActivatedAt     pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
	RevokedAt       pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	Revision        int64              `db:"revision" json:"revision"`
}

type AppIdentityEventReceipt struct {
	EventID         string             `db:"event_id" json:"event_id"`
	AuthSubject     string             `db:"auth_subject" json:"auth_subject"`
	EventType       string             `db:"event_type" json:"event_type"`
	SecurityVersion int64              `db:"security_version" json:"security_version"`
	ReceivedAt      pgtype.Timestamptz `db:"received_at" json:"received_at"`
	PayloadHash     string             `db:"payload_hash" json:"payload_hash"`
}

type AppLeetcodeMockInterviewRound struct {
	ID                      string             `db:"id" json:"id"`
	MockInterviewRoundID    string             `db:"mock_interview_round_id" json:"mock_interview_round_id"`
	LeetcodeProblemID       string             `db:"leetcode_problem_id" json:"leetcode_problem_id"`
	ClarifyQuestionScore    int16              `db:"clarify_question_score" json:"clarify_question_score"`
	AlgorithmDesignScore    int16              `db:"algorithm_design_score" json:"algorithm_design_score"`
	ComplexityAnalysisScore int16              `db:"complexity_analysis_score" json:"complexity_analysis_score"`
	CodingScore             int16              `db:"coding_score" json:"coding_score"`
	TestingScore            int16              `db:"testing_score" json:"testing_score"`
	DeletedAt               pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppLeetcodeProblem struct {
	ID             string               `db:"id" json:"id"`
	ProblemID      string               `db:"problem_id" json:"problem_id"`
	LeetcodeNumber int32                `db:"leetcode_number" json:"leetcode_number"`
	Difficulty     AppProblemDifficulty `db:"difficulty" json:"difficulty"`
	IsPremium      bool                 `db:"is_premium" json:"is_premium"`
	DeletedAt      pgtype.Timestamptz   `db:"deleted_at" json:"deleted_at"`
	Revision       int64                `db:"revision" json:"revision"`
	CreatedAt      pgtype.Timestamptz   `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz   `db:"updated_at" json:"updated_at"`
}

type AppLeetcodeProblemCategory struct {
	ID             string             `db:"id" json:"id"`
	Name           string             `db:"name" json:"name"`
	NormalizedName string             `db:"normalized_name" json:"normalized_name"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Revision       int64              `db:"revision" json:"revision"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppLeetcodeProblemCategoryMapping struct {
	LeetcodeProblemID string `db:"leetcode_problem_id" json:"leetcode_problem_id"`
	CategoryID        string `db:"category_id" json:"category_id"`
}

type AppLeetcodeSyncRun struct {
	ID                string             `db:"id" json:"id"`
	TriggerKind       string             `db:"trigger_kind" json:"trigger_kind"`
	RequestedByUserID *string            `db:"requested_by_user_id" json:"requested_by_user_id"`
	StartedAt         pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt        pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	Succeeded         *bool              `db:"succeeded" json:"succeeded"`
	FetchedCount      *int32             `db:"fetched_count" json:"fetched_count"`
	ChangedCount      *int32             `db:"changed_count" json:"changed_count"`
	ErrorSummary      *string            `db:"error_summary" json:"error_summary"`
}

type AppMentorship struct {
	ID                  string             `db:"id" json:"id"`
	SeasonID            string             `db:"season_id" json:"season_id"`
	MentorEnrollmentID  string             `db:"mentor_enrollment_id" json:"mentor_enrollment_id"`
	StudentEnrollmentID string             `db:"student_enrollment_id" json:"student_enrollment_id"`
	EndedAt             pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Revision            int64              `db:"revision" json:"revision"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppMockInterview struct {
	ID                       string             `db:"id" json:"id"`
	InterviewerUserID        string             `db:"interviewer_user_id" json:"interviewer_user_id"`
	IntervieweeUserID        string             `db:"interviewee_user_id" json:"interviewee_user_id"`
	SeasonID                 *string            `db:"season_id" json:"season_id"`
	SeasonWeekID             *string            `db:"season_week_id" json:"season_week_id"`
	ScheduledAt              pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	DurationMinutes          int32              `db:"duration_minutes" json:"duration_minutes"`
	LegacyIsPass             *bool              `db:"legacy_is_pass" json:"legacy_is_pass"`
	InterviewerNotesHtml     *string            `db:"interviewer_notes_html" json:"interviewer_notes_html"`
	NotesSanitizationChanged bool               `db:"notes_sanitization_changed" json:"notes_sanitization_changed"`
	DeletedAt                pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Revision                 int64              `db:"revision" json:"revision"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppMockInterviewRound struct {
	ID                        string             `db:"id" json:"id"`
	MockInterviewID           string             `db:"mock_interview_id" json:"mock_interview_id"`
	Position                  int32              `db:"position" json:"position"`
	Kind                      AppMockRoundKind   `db:"kind" json:"kind"`
	ReviewStatus              AppReviewStatus    `db:"review_status" json:"review_status"`
	IntervieweeCommentHtml    *string            `db:"interviewee_comment_html" json:"interviewee_comment_html"`
	ReviewSanitizationChanged bool               `db:"review_sanitization_changed" json:"review_sanitization_changed"`
	ReviewedAt                pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	DeletedAt                 pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Revision                  int64              `db:"revision" json:"revision"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppMockInterviewVersion struct {
	ID              string             `db:"id" json:"id"`
	MockInterviewID string             `db:"mock_interview_id" json:"mock_interview_id"`
	Version         int64              `db:"version" json:"version"`
	ActorUserID     *string            `db:"actor_user_id" json:"actor_user_id"`
	Reason          string             `db:"reason" json:"reason"`
	Snapshot        []byte             `db:"snapshot" json:"snapshot"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AppPracticeGoal struct {
	UserID          string             `db:"user_id" json:"user_id"`
	Enabled         bool               `db:"enabled" json:"enabled"`
	EnabledByUserID *string            `db:"enabled_by_user_id" json:"enabled_by_user_id"`
	EnabledAt       pgtype.Timestamptz `db:"enabled_at" json:"enabled_at"`
	EasyMinutes     int32              `db:"easy_minutes" json:"easy_minutes"`
	MediumMinutes   int32              `db:"medium_minutes" json:"medium_minutes"`
	HardMinutes     int32              `db:"hard_minutes" json:"hard_minutes"`
	Revision        int64              `db:"revision" json:"revision"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppProblem struct {
	ID        string             `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	Url       *string            `db:"url" json:"url"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Revision  int64              `db:"revision" json:"revision"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppProblemAttempt struct {
	ID                       string             `db:"id" json:"id"`
	UserID                   string             `db:"user_id" json:"user_id"`
	ProblemID                string             `db:"problem_id" json:"problem_id"`
	EnrollmentID             *string            `db:"enrollment_id" json:"enrollment_id"`
	SeasonWeekID             *string            `db:"season_week_id" json:"season_week_id"`
	AttemptedAt              pgtype.Timestamptz `db:"attempted_at" json:"attempted_at"`
	TimeTakenMinutes         int32              `db:"time_taken_minutes" json:"time_taken_minutes"`
	Outcome                  AppAttemptOutcome  `db:"outcome" json:"outcome"`
	Confidence               *int16             `db:"confidence" json:"confidence"`
	NotesHtml                *string            `db:"notes_html" json:"notes_html"`
	NotesSanitizationChanged bool               `db:"notes_sanitization_changed" json:"notes_sanitization_changed"`
	DeletedAt                pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Revision                 int64              `db:"revision" json:"revision"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppRecommendation struct {
	ID                   string                 `db:"id" json:"id"`
	UserID               string                 `db:"user_id" json:"user_id"`
	LeetcodeProblemID    string                 `db:"leetcode_problem_id" json:"leetcode_problem_id"`
	CategoryID           *string                `db:"category_id" json:"category_id"`
	Difficulty           AppProblemDifficulty   `db:"difficulty" json:"difficulty"`
	Rationale            string                 `db:"rationale" json:"rationale"`
	RuleVersion          string                 `db:"rule_version" json:"rule_version"`
	State                AppRecommendationState `db:"state" json:"state"`
	GeneratedAt          pgtype.Timestamptz     `db:"generated_at" json:"generated_at"`
	FulfilledByAttemptID *string                `db:"fulfilled_by_attempt_id" json:"fulfilled_by_attempt_id"`
	StateChangedAt       pgtype.Timestamptz     `db:"state_changed_at" json:"state_changed_at"`
	DeletedAt            pgtype.Timestamptz     `db:"deleted_at" json:"deleted_at"`
	Revision             int64                  `db:"revision" json:"revision"`
	CreatedAt            pgtype.Timestamptz     `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz     `db:"updated_at" json:"updated_at"`
}

type AppRecommendationDismissal struct {
	ID                string             `db:"id" json:"id"`
	RecommendationID  string             `db:"recommendation_id" json:"recommendation_id"`
	UserID            string             `db:"user_id" json:"user_id"`
	LeetcodeProblemID string             `db:"leetcode_problem_id" json:"leetcode_problem_id"`
	Reason            *string            `db:"reason" json:"reason"`
	DismissedAt       pgtype.Timestamptz `db:"dismissed_at" json:"dismissed_at"`
	ExcludedUntil     pgtype.Timestamptz `db:"excluded_until" json:"excluded_until"`
}

type AppSeason struct {
	ID                   string             `db:"id" json:"id"`
	Slug                 string             `db:"slug" json:"slug"`
	Name                 string             `db:"name" json:"name"`
	Status               AppSeasonStatus    `db:"status" json:"status"`
	StartAt              pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt                pgtype.Timestamptz `db:"end_at" json:"end_at"`
	Location             string             `db:"location" json:"location"`
	ImageUrl             string             `db:"image_url" json:"image_url"`
	ResourcesUrl         string             `db:"resources_url" json:"resources_url"`
	LegacyDataBackfilled *bool              `db:"legacy_data_backfilled" json:"legacy_data_backfilled"`
	ClosedAt             pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	DeletedAt            pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Revision             int64              `db:"revision" json:"revision"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppSeasonCloseEvent struct {
	ID               string             `db:"id" json:"id"`
	SeasonID         string             `db:"season_id" json:"season_id"`
	ClosedByUserID   *string            `db:"closed_by_user_id" json:"closed_by_user_id"`
	CloseReason      string             `db:"close_reason" json:"close_reason"`
	ClosedAt         pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	ReopenedByUserID *string            `db:"reopened_by_user_id" json:"reopened_by_user_id"`
	ReopenReason     *string            `db:"reopen_reason" json:"reopen_reason"`
	ReopenedAt       pgtype.Timestamptz `db:"reopened_at" json:"reopened_at"`
	MigrationRunID   *string            `db:"migration_run_id" json:"migration_run_id"`
}

type AppSeasonWeek struct {
	ID          string             `db:"id" json:"id"`
	SeasonID    string             `db:"season_id" json:"season_id"`
	WeekNumber  int32              `db:"week_number" json:"week_number"`
	StartAt     pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt       pgtype.Timestamptz `db:"end_at" json:"end_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Revision    int64              `db:"revision" json:"revision"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ResourceUrl string             `db:"resource_url" json:"resource_url"`
}

type AppUser struct {
	ID                   string             `db:"id" json:"id"`
	Slug                 string             `db:"slug" json:"slug"`
	DisplayName          string             `db:"display_name" json:"display_name"`
	Email                *string            `db:"email" json:"email"`
	DiscordID            *string            `db:"discord_id" json:"discord_id"`
	AvatarUrl            *string            `db:"avatar_url" json:"avatar_url"`
	AccountState         AppAccountState    `db:"account_state" json:"account_state"`
	Timezone             string             `db:"timezone" json:"timezone"`
	IsTest               bool               `db:"is_test" json:"is_test"`
	LeetcodePremiumOptIn bool               `db:"leetcode_premium_opt_in" json:"leetcode_premium_opt_in"`
	LegacyIsAdmin        *bool              `db:"legacy_is_admin" json:"legacy_is_admin"`
	LegacyIsGraduate     *bool              `db:"legacy_is_graduate" json:"legacy_is_graduate"`
	SuspendedAt          pgtype.Timestamptz `db:"suspended_at" json:"suspended_at"`
	DeletionRequestedAt  pgtype.Timestamptz `db:"deletion_requested_at" json:"deletion_requested_at"`
	DeletionDueAt        pgtype.Timestamptz `db:"deletion_due_at" json:"deletion_due_at"`
	PseudonymizedAt      pgtype.Timestamptz `db:"pseudonymized_at" json:"pseudonymized_at"`
	DeletedAt            pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Revision             int64              `db:"revision" json:"revision"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SecurityVersion      int64              `db:"security_version" json:"security_version"`
	TimezoneConfigured   bool               `db:"timezone_configured" json:"timezone_configured"`
	MfaConfigured        bool               `db:"mfa_configured" json:"mfa_configured"`
}

type AppUserAuthLink struct {
	AuthSubject       string             `db:"auth_subject" json:"auth_subject"`
	UserID            string             `db:"user_id" json:"user_id"`
	Provider          string             `db:"provider" json:"provider"`
	ProviderAccountID string             `db:"provider_account_id" json:"provider_account_id"`
	Active            bool               `db:"active" json:"active"`
	LinkedAt          pgtype.Timestamptz `db:"linked_at" json:"linked_at"`
	RevokedAt         pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type MigrationAnomaly struct {
	RunID              string                   `db:"run_id" json:"run_id"`
	Code               string                   `db:"code" json:"code"`
	SourceTable        string                   `db:"source_table" json:"source_table"`
	SourceID           string                   `db:"source_id" json:"source_id"`
	Severity           MigrationAnomalySeverity `db:"severity" json:"severity"`
	Detail             string                   `db:"detail" json:"detail"`
	Context            []byte                   `db:"context" json:"context"`
	ResolutionChecksum *string                  `db:"resolution_checksum" json:"resolution_checksum"`
}

type MigrationAuth0IdentityImport struct {
	RunID                  string  `db:"run_id" json:"run_id"`
	Auth0UserID            string  `db:"auth0_user_id" json:"auth0_user_id"`
	AppUserID              *string `db:"app_user_id" json:"app_user_id"`
	Provider               *string `db:"provider" json:"provider"`
	ProviderAccountID      *string `db:"provider_account_id" json:"provider_account_id"`
	EmailVerified          *bool   `db:"email_verified" json:"email_verified"`
	PasswordHashCompatible *bool   `db:"password_hash_compatible" json:"password_hash_compatible"`
	Status                 string  `db:"status" json:"status"`
	Detail                 *string `db:"detail" json:"detail"`
}

type MigrationAutoFix struct {
	RunID       string             `db:"run_id" json:"run_id"`
	SourceTable string             `db:"source_table" json:"source_table"`
	SourceID    string             `db:"source_id" json:"source_id"`
	Code        string             `db:"code" json:"code"`
	BeforeValue []byte             `db:"before_value" json:"before_value"`
	AfterValue  []byte             `db:"after_value" json:"after_value"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MigrationResolution struct {
	RunID                  string                    `db:"run_id" json:"run_id"`
	AnomalyCode            string                    `db:"anomaly_code" json:"anomaly_code"`
	SourceTable            string                    `db:"source_table" json:"source_table"`
	SourceID               string                    `db:"source_id" json:"source_id"`
	Action                 MigrationResolutionAction `db:"action" json:"action"`
	Value                  []byte                    `db:"value" json:"value"`
	ResolutionFileChecksum string                    `db:"resolution_file_checksum" json:"resolution_file_checksum"`
	AppliedAt              pgtype.Timestamptz        `db:"applied_at" json:"applied_at"`
}

type MigrationRowProvenance struct {
	RunID               string  `db:"run_id" json:"run_id"`
	SourceTable         string  `db:"source_table" json:"source_table"`
	SourceID            string  `db:"source_id" json:"source_id"`
	TargetTable         string  `db:"target_table" json:"target_table"`
	TargetID            string  `db:"target_id" json:"target_id"`
	SourceChecksum      string  `db:"source_checksum" json:"source_checksum"`
	TransformedChecksum string  `db:"transformed_checksum" json:"transformed_checksum"`
	TransformedData     []byte  `db:"transformed_data" json:"transformed_data"`
	DuplicateGroup      *string `db:"duplicate_group" json:"duplicate_group"`
}

type MigrationRun struct {
	ID                      string               `db:"id" json:"id"`
	ManifestChecksum        string               `db:"manifest_checksum" json:"manifest_checksum"`
	SourceSchemaFingerprint string               `db:"source_schema_fingerprint" json:"source_schema_fingerprint"`
	SourceSnapshotAt        pgtype.Timestamptz   `db:"source_snapshot_at" json:"source_snapshot_at"`
	State                   AppMigrationRunState `db:"state" json:"state"`
	StartedAt               pgtype.Timestamptz   `db:"started_at" json:"started_at"`
	FinishedAt              pgtype.Timestamptz   `db:"finished_at" json:"finished_at"`
	RolledBackAt            pgtype.Timestamptz   `db:"rolled_back_at" json:"rolled_back_at"`
	ErrorSummary            *string              `db:"error_summary" json:"error_summary"`
	CreatedAt               pgtype.Timestamptz   `db:"created_at" json:"created_at"`
}

type MigrationSourceTable struct {
	RunID               string `db:"run_id" json:"run_id"`
	SourceTable         string `db:"source_table" json:"source_table"`
	SourceCount         int64  `db:"source_count" json:"source_count"`
	ImportedCount       int64  `db:"imported_count" json:"imported_count"`
	SourceIdsChecksum   string `db:"source_ids_checksum" json:"source_ids_checksum"`
	TransformedChecksum string `db:"transformed_checksum" json:"transformed_checksum"`
}
