// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: practice.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProblemAttempt = `-- name: CreateProblemAttempt :one
INSERT INTO app.problem_attempts (
  id, user_id, problem_id, enrollment_id, season_week_id, attempted_at,
  time_taken_minutes, outcome, confidence, notes_html
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $9,
  $10
)
RETURNING id, user_id, problem_id, enrollment_id, season_week_id, attempted_at, time_taken_minutes, outcome, confidence, notes_html, notes_sanitization_changed, deleted_at, revision, created_at, updated_at
`

type CreateProblemAttemptParams struct {
	ID               string             `db:"id" json:"id"`
	UserID           string             `db:"user_id" json:"user_id"`
	ProblemID        string             `db:"problem_id" json:"problem_id"`
	EnrollmentID     *string            `db:"enrollment_id" json:"enrollment_id"`
	SeasonWeekID     *string            `db:"season_week_id" json:"season_week_id"`
	AttemptedAt      pgtype.Timestamptz `db:"attempted_at" json:"attempted_at"`
	TimeTakenMinutes int32              `db:"time_taken_minutes" json:"time_taken_minutes"`
	Outcome          AppAttemptOutcome  `db:"outcome" json:"outcome"`
	Confidence       *int16             `db:"confidence" json:"confidence"`
	NotesHtml        *string            `db:"notes_html" json:"notes_html"`
}

func (q *Queries) CreateProblemAttempt(ctx context.Context, arg CreateProblemAttemptParams) (AppProblemAttempt, error) {
	row := q.db.QueryRow(ctx, createProblemAttempt,
		arg.ID,
		arg.UserID,
		arg.ProblemID,
		arg.EnrollmentID,
		arg.SeasonWeekID,
		arg.AttemptedAt,
		arg.TimeTakenMinutes,
		arg.Outcome,
		arg.Confidence,
		arg.NotesHtml,
	)
	var i AppProblemAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.EnrollmentID,
		&i.SeasonWeekID,
		&i.AttemptedAt,
		&i.TimeTakenMinutes,
		&i.Outcome,
		&i.Confidence,
		&i.NotesHtml,
		&i.NotesSanitizationChanged,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecommendation = `-- name: CreateRecommendation :one
INSERT INTO app.recommendations (
  id, user_id, leetcode_problem_id, category_id, difficulty,
  rationale, rule_version, generated_at
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8
)
RETURNING id, user_id, leetcode_problem_id, category_id, difficulty, rationale, rule_version, state, generated_at, fulfilled_by_attempt_id, state_changed_at, deleted_at, revision, created_at, updated_at
`

type CreateRecommendationParams struct {
	ID                string               `db:"id" json:"id"`
	UserID            string               `db:"user_id" json:"user_id"`
	LeetcodeProblemID string               `db:"leetcode_problem_id" json:"leetcode_problem_id"`
	CategoryID        *string              `db:"category_id" json:"category_id"`
	Difficulty        AppProblemDifficulty `db:"difficulty" json:"difficulty"`
	Rationale         string               `db:"rationale" json:"rationale"`
	RuleVersion       string               `db:"rule_version" json:"rule_version"`
	GeneratedAt       pgtype.Timestamptz   `db:"generated_at" json:"generated_at"`
}

func (q *Queries) CreateRecommendation(ctx context.Context, arg CreateRecommendationParams) (AppRecommendation, error) {
	row := q.db.QueryRow(ctx, createRecommendation,
		arg.ID,
		arg.UserID,
		arg.LeetcodeProblemID,
		arg.CategoryID,
		arg.Difficulty,
		arg.Rationale,
		arg.RuleVersion,
		arg.GeneratedAt,
	)
	var i AppRecommendation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LeetcodeProblemID,
		&i.CategoryID,
		&i.Difficulty,
		&i.Rationale,
		&i.RuleVersion,
		&i.State,
		&i.GeneratedAt,
		&i.FulfilledByAttemptID,
		&i.StateChangedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dismissRecommendation = `-- name: DismissRecommendation :one
UPDATE app.recommendations
SET state = 'dismissed', state_changed_at = $1, revision = revision + 1
WHERE id = $2
  AND user_id = $3
  AND state = 'active'
  AND revision = $4
RETURNING id, user_id, leetcode_problem_id, category_id, difficulty, rationale, rule_version, state, generated_at, fulfilled_by_attempt_id, state_changed_at, deleted_at, revision, created_at, updated_at
`

type DismissRecommendationParams struct {
	DismissedAt pgtype.Timestamptz `db:"dismissed_at" json:"dismissed_at"`
	ID          string             `db:"id" json:"id"`
	UserID      string             `db:"user_id" json:"user_id"`
	Revision    int64              `db:"revision" json:"revision"`
}

func (q *Queries) DismissRecommendation(ctx context.Context, arg DismissRecommendationParams) (AppRecommendation, error) {
	row := q.db.QueryRow(ctx, dismissRecommendation,
		arg.DismissedAt,
		arg.ID,
		arg.UserID,
		arg.Revision,
	)
	var i AppRecommendation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LeetcodeProblemID,
		&i.CategoryID,
		&i.Difficulty,
		&i.Rationale,
		&i.RuleVersion,
		&i.State,
		&i.GeneratedAt,
		&i.FulfilledByAttemptID,
		&i.StateChangedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveRecommendation = `-- name: GetActiveRecommendation :one
SELECT r.id, r.user_id, r.leetcode_problem_id, r.category_id, r.difficulty, r.rationale, r.rule_version, r.state, r.generated_at, r.fulfilled_by_attempt_id, r.state_changed_at, r.deleted_at, r.revision, r.created_at, r.updated_at, lp.problem_id, lp.leetcode_number, lp.is_premium,
       p.title, p.url, c.name AS category_name
FROM app.recommendations AS r
JOIN app.leetcode_problems AS lp ON lp.id = r.leetcode_problem_id
JOIN app.problems AS p ON p.id = lp.problem_id
LEFT JOIN app.leetcode_problem_categories AS c ON c.id = r.category_id
WHERE r.user_id = $1 AND r.state = 'active' AND r.deleted_at IS NULL
`

type GetActiveRecommendationParams struct {
	UserID string `db:"user_id" json:"user_id"`
}

type GetActiveRecommendationRow struct {
	ID                   string                 `db:"id" json:"id"`
	UserID               string                 `db:"user_id" json:"user_id"`
	LeetcodeProblemID    string                 `db:"leetcode_problem_id" json:"leetcode_problem_id"`
	CategoryID           *string                `db:"category_id" json:"category_id"`
	Difficulty           AppProblemDifficulty   `db:"difficulty" json:"difficulty"`
	Rationale            string                 `db:"rationale" json:"rationale"`
	RuleVersion          string                 `db:"rule_version" json:"rule_version"`
	State                AppRecommendationState `db:"state" json:"state"`
	GeneratedAt          pgtype.Timestamptz     `db:"generated_at" json:"generated_at"`
	FulfilledByAttemptID *string                `db:"fulfilled_by_attempt_id" json:"fulfilled_by_attempt_id"`
	StateChangedAt       pgtype.Timestamptz     `db:"state_changed_at" json:"state_changed_at"`
	DeletedAt            pgtype.Timestamptz     `db:"deleted_at" json:"deleted_at"`
	Revision             int64                  `db:"revision" json:"revision"`
	CreatedAt            pgtype.Timestamptz     `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz     `db:"updated_at" json:"updated_at"`
	ProblemID            string                 `db:"problem_id" json:"problem_id"`
	LeetcodeNumber       int32                  `db:"leetcode_number" json:"leetcode_number"`
	IsPremium            bool                   `db:"is_premium" json:"is_premium"`
	Title                string                 `db:"title" json:"title"`
	Url                  *string                `db:"url" json:"url"`
	CategoryName         *string                `db:"category_name" json:"category_name"`
}

func (q *Queries) GetActiveRecommendation(ctx context.Context, arg GetActiveRecommendationParams) (GetActiveRecommendationRow, error) {
	row := q.db.QueryRow(ctx, getActiveRecommendation, arg.UserID)
	var i GetActiveRecommendationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LeetcodeProblemID,
		&i.CategoryID,
		&i.Difficulty,
		&i.Rationale,
		&i.RuleVersion,
		&i.State,
		&i.GeneratedAt,
		&i.FulfilledByAttemptID,
		&i.StateChangedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProblemID,
		&i.LeetcodeNumber,
		&i.IsPremium,
		&i.Title,
		&i.Url,
		&i.CategoryName,
	)
	return i, err
}

const listLeetcodeProblems = `-- name: ListLeetcodeProblems :many
SELECT lp.id, lp.problem_id, lp.leetcode_number, lp.difficulty, lp.is_premium, lp.deleted_at, lp.revision, lp.created_at, lp.updated_at, p.title, p.url,
       COALESCE(array_agg(c.normalized_name ORDER BY c.normalized_name)
         FILTER (WHERE c.id IS NOT NULL), ARRAY[]::text[]) AS categories
FROM app.leetcode_problems AS lp
JOIN app.problems AS p ON p.id = lp.problem_id
LEFT JOIN app.leetcode_problem_category_mappings AS pcm ON pcm.leetcode_problem_id = lp.id
LEFT JOIN app.leetcode_problem_categories AS c ON c.id = pcm.category_id AND c.deleted_at IS NULL
WHERE lp.deleted_at IS NULL
  AND p.deleted_at IS NULL
  AND ($1::app.problem_difficulty IS NULL OR lp.difficulty = $1)
  AND ($2::boolean IS NULL OR lp.is_premium = $2)
  AND ($3::text IS NULL OR (lp.leetcode_number, lp.id) > ($4::integer, $3::text))
GROUP BY lp.id, p.id
ORDER BY lp.leetcode_number ASC, lp.id ASC
LIMIT $5
`

type ListLeetcodeProblemsParams struct {
	Difficulty  NullAppProblemDifficulty `db:"difficulty" json:"difficulty"`
	IsPremium   *bool                    `db:"is_premium" json:"is_premium"`
	AfterID     *string                  `db:"after_id" json:"after_id"`
	AfterNumber *int32                   `db:"after_number" json:"after_number"`
	PageLimit   int32                    `db:"page_limit" json:"page_limit"`
}

type ListLeetcodeProblemsRow struct {
	ID             string               `db:"id" json:"id"`
	ProblemID      string               `db:"problem_id" json:"problem_id"`
	LeetcodeNumber int32                `db:"leetcode_number" json:"leetcode_number"`
	Difficulty     AppProblemDifficulty `db:"difficulty" json:"difficulty"`
	IsPremium      bool                 `db:"is_premium" json:"is_premium"`
	DeletedAt      pgtype.Timestamptz   `db:"deleted_at" json:"deleted_at"`
	Revision       int64                `db:"revision" json:"revision"`
	CreatedAt      pgtype.Timestamptz   `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz   `db:"updated_at" json:"updated_at"`
	Title          string               `db:"title" json:"title"`
	Url            *string              `db:"url" json:"url"`
	Categories     interface{}          `db:"categories" json:"categories"`
}

func (q *Queries) ListLeetcodeProblems(ctx context.Context, arg ListLeetcodeProblemsParams) ([]ListLeetcodeProblemsRow, error) {
	rows, err := q.db.Query(ctx, listLeetcodeProblems,
		arg.Difficulty,
		arg.IsPremium,
		arg.AfterID,
		arg.AfterNumber,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeetcodeProblemsRow{}
	for rows.Next() {
		var i ListLeetcodeProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.LeetcodeNumber,
			&i.Difficulty,
			&i.IsPremium,
			&i.DeletedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemAttemptsForUser = `-- name: ListProblemAttemptsForUser :many
SELECT pa.id, pa.user_id, pa.problem_id, pa.enrollment_id, pa.season_week_id, pa.attempted_at, pa.time_taken_minutes, pa.outcome, pa.confidence, pa.notes_html, pa.notes_sanitization_changed, pa.deleted_at, pa.revision, pa.created_at, pa.updated_at, p.title, p.url, lp.leetcode_number, lp.difficulty, lp.is_premium
FROM app.problem_attempts AS pa
JOIN app.problems AS p ON p.id = pa.problem_id
LEFT JOIN app.leetcode_problems AS lp ON lp.problem_id = p.id
WHERE pa.user_id = $1
  AND pa.deleted_at IS NULL
  AND ($2::app.attempt_outcome IS NULL OR pa.outcome = $2)
  AND ($3::text IS NULL OR (pa.attempted_at, pa.id) < ($4::timestamptz, $3::text))
ORDER BY pa.attempted_at DESC, pa.id DESC
LIMIT $5
`

type ListProblemAttemptsForUserParams struct {
	UserID    string                `db:"user_id" json:"user_id"`
	Outcome   NullAppAttemptOutcome `db:"outcome" json:"outcome"`
	AfterID   *string               `db:"after_id" json:"after_id"`
	AfterAt   pgtype.Timestamptz    `db:"after_at" json:"after_at"`
	PageLimit int32                 `db:"page_limit" json:"page_limit"`
}

type ListProblemAttemptsForUserRow struct {
	ID                       string                   `db:"id" json:"id"`
	UserID                   string                   `db:"user_id" json:"user_id"`
	ProblemID                string                   `db:"problem_id" json:"problem_id"`
	EnrollmentID             *string                  `db:"enrollment_id" json:"enrollment_id"`
	SeasonWeekID             *string                  `db:"season_week_id" json:"season_week_id"`
	AttemptedAt              pgtype.Timestamptz       `db:"attempted_at" json:"attempted_at"`
	TimeTakenMinutes         int32                    `db:"time_taken_minutes" json:"time_taken_minutes"`
	Outcome                  AppAttemptOutcome        `db:"outcome" json:"outcome"`
	Confidence               *int16                   `db:"confidence" json:"confidence"`
	NotesHtml                *string                  `db:"notes_html" json:"notes_html"`
	NotesSanitizationChanged bool                     `db:"notes_sanitization_changed" json:"notes_sanitization_changed"`
	DeletedAt                pgtype.Timestamptz       `db:"deleted_at" json:"deleted_at"`
	Revision                 int64                    `db:"revision" json:"revision"`
	CreatedAt                pgtype.Timestamptz       `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	Title                    string                   `db:"title" json:"title"`
	Url                      *string                  `db:"url" json:"url"`
	LeetcodeNumber           *int32                   `db:"leetcode_number" json:"leetcode_number"`
	Difficulty               NullAppProblemDifficulty `db:"difficulty" json:"difficulty"`
	IsPremium                *bool                    `db:"is_premium" json:"is_premium"`
}

func (q *Queries) ListProblemAttemptsForUser(ctx context.Context, arg ListProblemAttemptsForUserParams) ([]ListProblemAttemptsForUserRow, error) {
	rows, err := q.db.Query(ctx, listProblemAttemptsForUser,
		arg.UserID,
		arg.Outcome,
		arg.AfterID,
		arg.AfterAt,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProblemAttemptsForUserRow{}
	for rows.Next() {
		var i ListProblemAttemptsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.EnrollmentID,
			&i.SeasonWeekID,
			&i.AttemptedAt,
			&i.TimeTakenMinutes,
			&i.Outcome,
			&i.Confidence,
			&i.NotesHtml,
			&i.NotesSanitizationChanged,
			&i.DeletedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.LeetcodeNumber,
			&i.Difficulty,
			&i.IsPremium,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRecommendationDismissal = `-- name: RecordRecommendationDismissal :one
INSERT INTO app.recommendation_dismissals (
  id, recommendation_id, user_id, leetcode_problem_id, reason,
  dismissed_at, excluded_until
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7
)
RETURNING id, recommendation_id, user_id, leetcode_problem_id, reason, dismissed_at, excluded_until
`

type RecordRecommendationDismissalParams struct {
	ID                string             `db:"id" json:"id"`
	RecommendationID  string             `db:"recommendation_id" json:"recommendation_id"`
	UserID            string             `db:"user_id" json:"user_id"`
	LeetcodeProblemID string             `db:"leetcode_problem_id" json:"leetcode_problem_id"`
	Reason            *string            `db:"reason" json:"reason"`
	DismissedAt       pgtype.Timestamptz `db:"dismissed_at" json:"dismissed_at"`
	ExcludedUntil     pgtype.Timestamptz `db:"excluded_until" json:"excluded_until"`
}

func (q *Queries) RecordRecommendationDismissal(ctx context.Context, arg RecordRecommendationDismissalParams) (AppRecommendationDismissal, error) {
	row := q.db.QueryRow(ctx, recordRecommendationDismissal,
		arg.ID,
		arg.RecommendationID,
		arg.UserID,
		arg.LeetcodeProblemID,
		arg.Reason,
		arg.DismissedAt,
		arg.ExcludedUntil,
	)
	var i AppRecommendationDismissal
	err := row.Scan(
		&i.ID,
		&i.RecommendationID,
		&i.UserID,
		&i.LeetcodeProblemID,
		&i.Reason,
		&i.DismissedAt,
		&i.ExcludedUntil,
	)
	return i, err
}

const softDeleteProblemAttempt = `-- name: SoftDeleteProblemAttempt :one
UPDATE app.problem_attempts
SET deleted_at = $1, revision = revision + 1
WHERE id = $2
  AND user_id = $3
  AND revision = $4
  AND deleted_at IS NULL
RETURNING revision
`

type SoftDeleteProblemAttemptParams struct {
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	ID        string             `db:"id" json:"id"`
	UserID    string             `db:"user_id" json:"user_id"`
	Revision  int64              `db:"revision" json:"revision"`
}

func (q *Queries) SoftDeleteProblemAttempt(ctx context.Context, arg SoftDeleteProblemAttemptParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteProblemAttempt,
		arg.DeletedAt,
		arg.ID,
		arg.UserID,
		arg.Revision,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const updateProblemAttempt = `-- name: UpdateProblemAttempt :one
UPDATE app.problem_attempts
SET attempted_at = $1,
    time_taken_minutes = $2,
    outcome = $3,
    confidence = $4,
    notes_html = $5,
    revision = revision + 1
WHERE id = $6
  AND user_id = $7
  AND revision = $8
  AND deleted_at IS NULL
RETURNING id, user_id, problem_id, enrollment_id, season_week_id, attempted_at, time_taken_minutes, outcome, confidence, notes_html, notes_sanitization_changed, deleted_at, revision, created_at, updated_at
`

type UpdateProblemAttemptParams struct {
	AttemptedAt      pgtype.Timestamptz `db:"attempted_at" json:"attempted_at"`
	TimeTakenMinutes int32              `db:"time_taken_minutes" json:"time_taken_minutes"`
	Outcome          AppAttemptOutcome  `db:"outcome" json:"outcome"`
	Confidence       *int16             `db:"confidence" json:"confidence"`
	NotesHtml        *string            `db:"notes_html" json:"notes_html"`
	ID               string             `db:"id" json:"id"`
	UserID           string             `db:"user_id" json:"user_id"`
	Revision         int64              `db:"revision" json:"revision"`
}

func (q *Queries) UpdateProblemAttempt(ctx context.Context, arg UpdateProblemAttemptParams) (AppProblemAttempt, error) {
	row := q.db.QueryRow(ctx, updateProblemAttempt,
		arg.AttemptedAt,
		arg.TimeTakenMinutes,
		arg.Outcome,
		arg.Confidence,
		arg.NotesHtml,
		arg.ID,
		arg.UserID,
		arg.Revision,
	)
	var i AppProblemAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.EnrollmentID,
		&i.SeasonWeekID,
		&i.AttemptedAt,
		&i.TimeTakenMinutes,
		&i.Outcome,
		&i.Confidence,
		&i.NotesHtml,
		&i.NotesSanitizationChanged,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
