// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seasons.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeActiveEnrollmentsForClose = `-- name: CompleteActiveEnrollmentsForClose :many
UPDATE app.enrollments
SET state = 'completed',
    completed_by_close_id = $1,
    state_changed_at = $2,
    assignment_state = 'revoked',
    activated_at = NULL,
    revision = revision + 1
WHERE season_id = $3
  AND state = 'active'
  AND deleted_at IS NULL
RETURNING id
`

type CompleteActiveEnrollmentsForCloseParams struct {
	CloseEventID *string            `db:"close_event_id" json:"close_event_id"`
	ClosedAt     pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	SeasonID     string             `db:"season_id" json:"season_id"`
}

func (q *Queries) CompleteActiveEnrollmentsForClose(ctx context.Context, arg CompleteActiveEnrollmentsForCloseParams) ([]string, error) {
	rows, err := q.db.Query(ctx, completeActiveEnrollmentsForClose, arg.CloseEventID, arg.ClosedAt, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSeason = `-- name: CreateSeason :one
INSERT INTO app.seasons (
  id, slug, name, status, start_at, end_at, location, image_url, resources_url
) VALUES (
  $1, $2, $3, 'open', $4,
  $5, $6, $7, $8
)
RETURNING id, slug, name, status, start_at, end_at, location, image_url, resources_url, legacy_data_backfilled, closed_at, deleted_at, revision, created_at, updated_at
`

type CreateSeasonParams struct {
	ID           string             `db:"id" json:"id"`
	Slug         string             `db:"slug" json:"slug"`
	Name         string             `db:"name" json:"name"`
	StartAt      pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt        pgtype.Timestamptz `db:"end_at" json:"end_at"`
	Location     string             `db:"location" json:"location"`
	ImageUrl     string             `db:"image_url" json:"image_url"`
	ResourcesUrl string             `db:"resources_url" json:"resources_url"`
}

func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (AppSeason, error) {
	row := q.db.QueryRow(ctx, createSeason,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.StartAt,
		arg.EndAt,
		arg.Location,
		arg.ImageUrl,
		arg.ResourcesUrl,
	)
	var i AppSeason
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.Location,
		&i.ImageUrl,
		&i.ResourcesUrl,
		&i.LegacyDataBackfilled,
		&i.ClosedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSeasonCloseEvent = `-- name: CreateSeasonCloseEvent :one
INSERT INTO app.season_close_events (
  id, season_id, closed_by_user_id, close_reason, closed_at, migration_run_id
) VALUES (
  $1, $2, $3,
  $4, $5, $6
)
RETURNING id, season_id, closed_by_user_id, close_reason, closed_at, reopened_by_user_id, reopen_reason, reopened_at, migration_run_id
`

type CreateSeasonCloseEventParams struct {
	ID             string             `db:"id" json:"id"`
	SeasonID       string             `db:"season_id" json:"season_id"`
	ActorUserID    *string            `db:"actor_user_id" json:"actor_user_id"`
	Reason         string             `db:"reason" json:"reason"`
	ClosedAt       pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	MigrationRunID *string            `db:"migration_run_id" json:"migration_run_id"`
}

func (q *Queries) CreateSeasonCloseEvent(ctx context.Context, arg CreateSeasonCloseEventParams) (AppSeasonCloseEvent, error) {
	row := q.db.QueryRow(ctx, createSeasonCloseEvent,
		arg.ID,
		arg.SeasonID,
		arg.ActorUserID,
		arg.Reason,
		arg.ClosedAt,
		arg.MigrationRunID,
	)
	var i AppSeasonCloseEvent
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.ClosedByUserID,
		&i.CloseReason,
		&i.ClosedAt,
		&i.ReopenedByUserID,
		&i.ReopenReason,
		&i.ReopenedAt,
		&i.MigrationRunID,
	)
	return i, err
}

const getSeasonByID = `-- name: GetSeasonByID :one
SELECT id, slug, name, status, start_at, end_at, location, image_url,
       resources_url, closed_at, revision, created_at, updated_at
FROM app.seasons
WHERE id = $1 AND deleted_at IS NULL
`

type GetSeasonByIDParams struct {
	ID string `db:"id" json:"id"`
}

type GetSeasonByIDRow struct {
	ID           string             `db:"id" json:"id"`
	Slug         string             `db:"slug" json:"slug"`
	Name         string             `db:"name" json:"name"`
	Status       AppSeasonStatus    `db:"status" json:"status"`
	StartAt      pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt        pgtype.Timestamptz `db:"end_at" json:"end_at"`
	Location     string             `db:"location" json:"location"`
	ImageUrl     string             `db:"image_url" json:"image_url"`
	ResourcesUrl string             `db:"resources_url" json:"resources_url"`
	ClosedAt     pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	Revision     int64              `db:"revision" json:"revision"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetSeasonByID(ctx context.Context, arg GetSeasonByIDParams) (GetSeasonByIDRow, error) {
	row := q.db.QueryRow(ctx, getSeasonByID, arg.ID)
	var i GetSeasonByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.Location,
		&i.ImageUrl,
		&i.ResourcesUrl,
		&i.ClosedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeasonBySlug = `-- name: GetSeasonBySlug :one
SELECT id, slug, name, status, start_at, end_at, location, image_url,
       resources_url, closed_at, revision, created_at, updated_at
FROM app.seasons
WHERE lower(slug) = lower($1) AND deleted_at IS NULL
`

type GetSeasonBySlugParams struct {
	Lower string `db:"lower" json:"lower"`
}

type GetSeasonBySlugRow struct {
	ID           string             `db:"id" json:"id"`
	Slug         string             `db:"slug" json:"slug"`
	Name         string             `db:"name" json:"name"`
	Status       AppSeasonStatus    `db:"status" json:"status"`
	StartAt      pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt        pgtype.Timestamptz `db:"end_at" json:"end_at"`
	Location     string             `db:"location" json:"location"`
	ImageUrl     string             `db:"image_url" json:"image_url"`
	ResourcesUrl string             `db:"resources_url" json:"resources_url"`
	ClosedAt     pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	Revision     int64              `db:"revision" json:"revision"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetSeasonBySlug(ctx context.Context, arg GetSeasonBySlugParams) (GetSeasonBySlugRow, error) {
	row := q.db.QueryRow(ctx, getSeasonBySlug, arg.Lower)
	var i GetSeasonBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.Location,
		&i.ImageUrl,
		&i.ResourcesUrl,
		&i.ClosedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSeasonWeeks = `-- name: ListSeasonWeeks :many
SELECT id, season_id, week_number, start_at, end_at, deleted_at, revision, created_at, updated_at, resource_url
FROM app.season_weeks
WHERE season_id = $1 AND deleted_at IS NULL
ORDER BY week_number ASC, id ASC
`

type ListSeasonWeeksParams struct {
	SeasonID string `db:"season_id" json:"season_id"`
}

func (q *Queries) ListSeasonWeeks(ctx context.Context, arg ListSeasonWeeksParams) ([]AppSeasonWeek, error) {
	rows, err := q.db.Query(ctx, listSeasonWeeks, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSeasonWeek{}
	for rows.Next() {
		var i AppSeasonWeek
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.WeekNumber,
			&i.StartAt,
			&i.EndAt,
			&i.DeletedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasons = `-- name: ListSeasons :many
SELECT id, slug, name, status, start_at, end_at, location, image_url,
       resources_url, closed_at, revision, created_at, updated_at
FROM app.seasons
WHERE deleted_at IS NULL
  AND ($1::app.season_status IS NULL OR status = $1)
  AND (
    $2::text IS NULL
    OR (start_at, id) < ($3::timestamptz, $2::text)
  )
ORDER BY start_at DESC, id DESC
LIMIT $4
`

type ListSeasonsParams struct {
	Status       NullAppSeasonStatus `db:"status" json:"status"`
	AfterID      *string             `db:"after_id" json:"after_id"`
	AfterStartAt pgtype.Timestamptz  `db:"after_start_at" json:"after_start_at"`
	PageLimit    int32               `db:"page_limit" json:"page_limit"`
}

type ListSeasonsRow struct {
	ID           string             `db:"id" json:"id"`
	Slug         string             `db:"slug" json:"slug"`
	Name         string             `db:"name" json:"name"`
	Status       AppSeasonStatus    `db:"status" json:"status"`
	StartAt      pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt        pgtype.Timestamptz `db:"end_at" json:"end_at"`
	Location     string             `db:"location" json:"location"`
	ImageUrl     string             `db:"image_url" json:"image_url"`
	ResourcesUrl string             `db:"resources_url" json:"resources_url"`
	ClosedAt     pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	Revision     int64              `db:"revision" json:"revision"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListSeasons(ctx context.Context, arg ListSeasonsParams) ([]ListSeasonsRow, error) {
	rows, err := q.db.Query(ctx, listSeasons,
		arg.Status,
		arg.AfterID,
		arg.AfterStartAt,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonsRow{}
	for rows.Next() {
		var i ListSeasonsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.Location,
			&i.ImageUrl,
			&i.ResourcesUrl,
			&i.ClosedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSeasonClosed = `-- name: MarkSeasonClosed :one
UPDATE app.seasons
SET status = 'closed',
    closed_at = $1,
    revision = revision + 1
WHERE id = $2
  AND status = 'open'
  AND revision = $3
  AND deleted_at IS NULL
RETURNING id, slug, name, status, start_at, end_at, location, image_url, resources_url, legacy_data_backfilled, closed_at, deleted_at, revision, created_at, updated_at
`

type MarkSeasonClosedParams struct {
	ClosedAt pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	ID       string             `db:"id" json:"id"`
	Revision int64              `db:"revision" json:"revision"`
}

func (q *Queries) MarkSeasonClosed(ctx context.Context, arg MarkSeasonClosedParams) (AppSeason, error) {
	row := q.db.QueryRow(ctx, markSeasonClosed, arg.ClosedAt, arg.ID, arg.Revision)
	var i AppSeason
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.Location,
		&i.ImageUrl,
		&i.ResourcesUrl,
		&i.LegacyDataBackfilled,
		&i.ClosedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSeasonOpen = `-- name: MarkSeasonOpen :one
UPDATE app.seasons
SET status = 'open', closed_at = NULL, revision = revision + 1
WHERE id = $1
  AND status = 'closed'
  AND revision = $2
  AND deleted_at IS NULL
RETURNING id, slug, name, status, start_at, end_at, location, image_url, resources_url, legacy_data_backfilled, closed_at, deleted_at, revision, created_at, updated_at
`

type MarkSeasonOpenParams struct {
	ID       string `db:"id" json:"id"`
	Revision int64  `db:"revision" json:"revision"`
}

func (q *Queries) MarkSeasonOpen(ctx context.Context, arg MarkSeasonOpenParams) (AppSeason, error) {
	row := q.db.QueryRow(ctx, markSeasonOpen, arg.ID, arg.Revision)
	var i AppSeason
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.Location,
		&i.ImageUrl,
		&i.ResourcesUrl,
		&i.LegacyDataBackfilled,
		&i.ClosedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reopenSeasonCloseEvent = `-- name: ReopenSeasonCloseEvent :one
UPDATE app.season_close_events
SET reopened_by_user_id = $1,
    reopen_reason = $2,
    reopened_at = $3
WHERE id = $4
  AND reopened_at IS NULL
RETURNING id, season_id, closed_by_user_id, close_reason, closed_at, reopened_by_user_id, reopen_reason, reopened_at, migration_run_id
`

type ReopenSeasonCloseEventParams struct {
	ActorUserID  *string            `db:"actor_user_id" json:"actor_user_id"`
	Reason       *string            `db:"reason" json:"reason"`
	ReopenedAt   pgtype.Timestamptz `db:"reopened_at" json:"reopened_at"`
	CloseEventID string             `db:"close_event_id" json:"close_event_id"`
}

func (q *Queries) ReopenSeasonCloseEvent(ctx context.Context, arg ReopenSeasonCloseEventParams) (AppSeasonCloseEvent, error) {
	row := q.db.QueryRow(ctx, reopenSeasonCloseEvent,
		arg.ActorUserID,
		arg.Reason,
		arg.ReopenedAt,
		arg.CloseEventID,
	)
	var i AppSeasonCloseEvent
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.ClosedByUserID,
		&i.CloseReason,
		&i.ClosedAt,
		&i.ReopenedByUserID,
		&i.ReopenReason,
		&i.ReopenedAt,
		&i.MigrationRunID,
	)
	return i, err
}

const restoreEnrollmentsForReopen = `-- name: RestoreEnrollmentsForReopen :many
UPDATE app.enrollments
SET state = 'active',
    completed_by_close_id = NULL,
    state_changed_at = $1,
    assignment_state = CASE WHEN role='coordinator' THEN 'pending_mfa' ELSE 'active' END,
    activated_at = CASE WHEN role='coordinator' THEN NULL ELSE $1 END,
    revision = revision + 1
WHERE completed_by_close_id = $2
  AND state = 'completed'
  AND deleted_at IS NULL
RETURNING id
`

type RestoreEnrollmentsForReopenParams struct {
	ReopenedAt   pgtype.Timestamptz `db:"reopened_at" json:"reopened_at"`
	CloseEventID *string            `db:"close_event_id" json:"close_event_id"`
}

func (q *Queries) RestoreEnrollmentsForReopen(ctx context.Context, arg RestoreEnrollmentsForReopenParams) ([]string, error) {
	rows, err := q.db.Query(ctx, restoreEnrollmentsForReopen, arg.ReopenedAt, arg.CloseEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeason = `-- name: UpdateSeason :one
UPDATE app.seasons
SET slug = $1,
    name = $2,
    start_at = $3,
    end_at = $4,
    location = $5,
    image_url = $6,
    resources_url = $7,
    revision = revision + 1
WHERE id = $8
  AND revision = $9
  AND deleted_at IS NULL
RETURNING id, slug, name, status, start_at, end_at, location, image_url, resources_url, legacy_data_backfilled, closed_at, deleted_at, revision, created_at, updated_at
`

type UpdateSeasonParams struct {
	Slug         string             `db:"slug" json:"slug"`
	Name         string             `db:"name" json:"name"`
	StartAt      pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt        pgtype.Timestamptz `db:"end_at" json:"end_at"`
	Location     string             `db:"location" json:"location"`
	ImageUrl     string             `db:"image_url" json:"image_url"`
	ResourcesUrl string             `db:"resources_url" json:"resources_url"`
	ID           string             `db:"id" json:"id"`
	Revision     int64              `db:"revision" json:"revision"`
}

func (q *Queries) UpdateSeason(ctx context.Context, arg UpdateSeasonParams) (AppSeason, error) {
	row := q.db.QueryRow(ctx, updateSeason,
		arg.Slug,
		arg.Name,
		arg.StartAt,
		arg.EndAt,
		arg.Location,
		arg.ImageUrl,
		arg.ResourcesUrl,
		arg.ID,
		arg.Revision,
	)
	var i AppSeason
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.Location,
		&i.ImageUrl,
		&i.ResourcesUrl,
		&i.LegacyDataBackfilled,
		&i.ClosedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSeasonWeek = `-- name: UpsertSeasonWeek :one
INSERT INTO app.season_weeks (
  id, season_id, week_number, start_at, end_at
) VALUES (
  $1, $2, $3,
  $4, $5
)
ON CONFLICT (season_id, week_number) DO UPDATE
SET start_at = EXCLUDED.start_at,
    end_at = EXCLUDED.end_at,
    revision = app.season_weeks.revision + 1
WHERE app.season_weeks.revision = $6
RETURNING id, season_id, week_number, start_at, end_at, deleted_at, revision, created_at, updated_at, resource_url
`

type UpsertSeasonWeekParams struct {
	ID               string             `db:"id" json:"id"`
	SeasonID         string             `db:"season_id" json:"season_id"`
	WeekNumber       int32              `db:"week_number" json:"week_number"`
	StartAt          pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt            pgtype.Timestamptz `db:"end_at" json:"end_at"`
	ExpectedRevision int64              `db:"expected_revision" json:"expected_revision"`
}

func (q *Queries) UpsertSeasonWeek(ctx context.Context, arg UpsertSeasonWeekParams) (AppSeasonWeek, error) {
	row := q.db.QueryRow(ctx, upsertSeasonWeek,
		arg.ID,
		arg.SeasonID,
		arg.WeekNumber,
		arg.StartAt,
		arg.EndAt,
		arg.ExpectedRevision,
	)
	var i AppSeasonWeek
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.WeekNumber,
		&i.StartAt,
		&i.EndAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceUrl,
	)
	return i, err
}
