// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const beginAccountDeletion = `-- name: BeginAccountDeletion :one
UPDATE app.users
SET account_state = 'deletion_pending',
    deletion_requested_at = $1,
    deletion_due_at = $2,
    revision = revision + 1
WHERE id = $3
  AND account_state = 'active'
  AND revision = $4
RETURNING id, slug, display_name, email, discord_id, avatar_url, account_state, timezone, is_test, leetcode_premium_opt_in, legacy_is_admin, legacy_is_graduate, suspended_at, deletion_requested_at, deletion_due_at, pseudonymized_at, deleted_at, revision, created_at, updated_at
`

type BeginAccountDeletionParams struct {
	RequestedAt pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	DueAt       pgtype.Timestamptz `db:"due_at" json:"due_at"`
	UserID      string             `db:"user_id" json:"user_id"`
	Revision    int64              `db:"revision" json:"revision"`
}

func (q *Queries) BeginAccountDeletion(ctx context.Context, arg BeginAccountDeletionParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, beginAccountDeletion,
		arg.RequestedAt,
		arg.DueAt,
		arg.UserID,
		arg.Revision,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Email,
		&i.DiscordID,
		&i.AvatarUrl,
		&i.AccountState,
		&i.Timezone,
		&i.IsTest,
		&i.LeetcodePremiumOptIn,
		&i.LegacyIsAdmin,
		&i.LegacyIsGraduate,
		&i.SuspendedAt,
		&i.DeletionRequestedAt,
		&i.DeletionDueAt,
		&i.PseudonymizedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelAccountDeletion = `-- name: CancelAccountDeletion :one
UPDATE app.users
SET account_state = 'active',
    deletion_requested_at = NULL,
    deletion_due_at = NULL,
    revision = revision + 1
WHERE id = $1
  AND account_state = 'deletion_pending'
RETURNING id, slug, display_name, email, discord_id, avatar_url, account_state, timezone, is_test, leetcode_premium_opt_in, legacy_is_admin, legacy_is_graduate, suspended_at, deletion_requested_at, deletion_due_at, pseudonymized_at, deleted_at, revision, created_at, updated_at
`

type CancelAccountDeletionParams struct {
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) CancelAccountDeletion(ctx context.Context, arg CancelAccountDeletionParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, cancelAccountDeletion, arg.UserID)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Email,
		&i.DiscordID,
		&i.AvatarUrl,
		&i.AccountState,
		&i.Timezone,
		&i.IsTest,
		&i.LeetcodePremiumOptIn,
		&i.LegacyIsAdmin,
		&i.LegacyIsGraduate,
		&i.SuspendedAt,
		&i.DeletionRequestedAt,
		&i.DeletionDueAt,
		&i.PseudonymizedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPrivateByID = `-- name: GetUserPrivateByID :one
SELECT id, slug, display_name, email, discord_id, avatar_url, account_state, timezone, is_test, leetcode_premium_opt_in, legacy_is_admin, legacy_is_graduate, suspended_at, deletion_requested_at, deletion_due_at, pseudonymized_at, deleted_at, revision, created_at, updated_at FROM app.users WHERE id = $1
`

type GetUserPrivateByIDParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) GetUserPrivateByID(ctx context.Context, arg GetUserPrivateByIDParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserPrivateByID, arg.ID)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Email,
		&i.DiscordID,
		&i.AvatarUrl,
		&i.AccountState,
		&i.Timezone,
		&i.IsTest,
		&i.LeetcodePremiumOptIn,
		&i.LegacyIsAdmin,
		&i.LegacyIsGraduate,
		&i.SuspendedAt,
		&i.DeletionRequestedAt,
		&i.DeletionDueAt,
		&i.PseudonymizedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPublicBySlug = `-- name: GetUserPublicBySlug :one
SELECT id, slug, display_name, avatar_url, timezone, created_at
FROM app.users
WHERE lower(slug) = lower($1)
  AND account_state = 'active'
  AND NOT is_test
  AND deleted_at IS NULL
`

type GetUserPublicBySlugParams struct {
	Lower string `db:"lower" json:"lower"`
}

type GetUserPublicBySlugRow struct {
	ID          string             `db:"id" json:"id"`
	Slug        string             `db:"slug" json:"slug"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   *string            `db:"avatar_url" json:"avatar_url"`
	Timezone    string             `db:"timezone" json:"timezone"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetUserPublicBySlug(ctx context.Context, arg GetUserPublicBySlugParams) (GetUserPublicBySlugRow, error) {
	row := q.db.QueryRow(ctx, getUserPublicBySlug, arg.Lower)
	var i GetUserPublicBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const isAlumni = `-- name: IsAlumni :one
SELECT EXISTS (
  SELECT 1
  FROM app.enrollments
  WHERE user_id = $1
    AND role = 'student'
    AND state = 'completed'
    AND deleted_at IS NULL
) AS is_alumni
`

type IsAlumniParams struct {
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) IsAlumni(ctx context.Context, arg IsAlumniParams) (bool, error) {
	row := q.db.QueryRow(ctx, isAlumni, arg.UserID)
	var is_alumni bool
	err := row.Scan(&is_alumni)
	return is_alumni, err
}

const listDeletionRequestsDue = `-- name: ListDeletionRequestsDue :many
SELECT r.id, r.user_id, r.recovery_token_hash, r.requested_at, r.expires_at, r.cancelled_at, r.completed_at, u.revision AS user_revision
FROM app.account_deletion_requests AS r
JOIN app.users AS u ON u.id = r.user_id
WHERE r.cancelled_at IS NULL
  AND r.completed_at IS NULL
  AND r.expires_at <= $1
  AND u.account_state = 'deletion_pending'
ORDER BY r.expires_at, r.id
LIMIT $2
FOR UPDATE OF r, u SKIP LOCKED
`

type ListDeletionRequestsDueParams struct {
	NowAt      pgtype.Timestamptz `db:"now_at" json:"now_at"`
	BatchLimit int32              `db:"batch_limit" json:"batch_limit"`
}

type ListDeletionRequestsDueRow struct {
	ID                string             `db:"id" json:"id"`
	UserID            string             `db:"user_id" json:"user_id"`
	RecoveryTokenHash string             `db:"recovery_token_hash" json:"recovery_token_hash"`
	RequestedAt       pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CancelledAt       pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	CompletedAt       pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	UserRevision      int64              `db:"user_revision" json:"user_revision"`
}

func (q *Queries) ListDeletionRequestsDue(ctx context.Context, arg ListDeletionRequestsDueParams) ([]ListDeletionRequestsDueRow, error) {
	rows, err := q.db.Query(ctx, listDeletionRequestsDue, arg.NowAt, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletionRequestsDueRow{}
	for rows.Next() {
		var i ListDeletionRequestsDueRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RecoveryTokenHash,
			&i.RequestedAt,
			&i.ExpiresAt,
			&i.CancelledAt,
			&i.CompletedAt,
			&i.UserRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectoryUsers = `-- name: ListDirectoryUsers :many
SELECT DISTINCT u.id, u.slug, u.display_name, u.avatar_url, u.timezone, u.created_at
FROM app.users AS u
JOIN app.enrollments AS e ON e.user_id = u.id
WHERE u.account_state = 'active'
  AND NOT u.is_test
  AND u.deleted_at IS NULL
  AND e.deleted_at IS NULL
  AND e.state IN ('active', 'completed')
  AND ($1::text IS NULL OR (u.display_name, u.id) > ($2::text, $1::text))
ORDER BY u.display_name ASC, u.id ASC
LIMIT $3
`

type ListDirectoryUsersParams struct {
	AfterID   *string `db:"after_id" json:"after_id"`
	AfterName *string `db:"after_name" json:"after_name"`
	PageLimit int32   `db:"page_limit" json:"page_limit"`
}

type ListDirectoryUsersRow struct {
	ID          string             `db:"id" json:"id"`
	Slug        string             `db:"slug" json:"slug"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   *string            `db:"avatar_url" json:"avatar_url"`
	Timezone    string             `db:"timezone" json:"timezone"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListDirectoryUsers(ctx context.Context, arg ListDirectoryUsersParams) ([]ListDirectoryUsersRow, error) {
	rows, err := q.db.Query(ctx, listDirectoryUsers, arg.AfterID, arg.AfterName, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirectoryUsersRow{}
	for rows.Next() {
		var i ListDirectoryUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalRolesForUser = `-- name: ListGlobalRolesForUser :many
SELECT role, state, granted_at, activated_at
FROM app.global_role_assignments
WHERE user_id = $1 AND state <> 'revoked'
ORDER BY role
`

type ListGlobalRolesForUserParams struct {
	UserID string `db:"user_id" json:"user_id"`
}

type ListGlobalRolesForUserRow struct {
	Role        AppGlobalRole      `db:"role" json:"role"`
	State       AppAssignmentState `db:"state" json:"state"`
	GrantedAt   pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	ActivatedAt pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
}

func (q *Queries) ListGlobalRolesForUser(ctx context.Context, arg ListGlobalRolesForUserParams) ([]ListGlobalRolesForUserRow, error) {
	rows, err := q.db.Query(ctx, listGlobalRolesForUser, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGlobalRolesForUserRow{}
	for rows.Next() {
		var i ListGlobalRolesForUserRow
		if err := rows.Scan(
			&i.Role,
			&i.State,
			&i.GrantedAt,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveActiveAuthSubject = `-- name: ResolveActiveAuthSubject :one
SELECT u.id, u.slug, u.display_name, u.email, u.discord_id, u.avatar_url, u.account_state, u.timezone, u.is_test, u.leetcode_premium_opt_in, u.legacy_is_admin, u.legacy_is_graduate, u.suspended_at, u.deletion_requested_at, u.deletion_due_at, u.pseudonymized_at, u.deleted_at, u.revision, u.created_at, u.updated_at
FROM app.user_auth_links AS l
JOIN app.users AS u ON u.id = l.user_id
WHERE l.auth_subject = $1
  AND l.active
  AND u.account_state = 'active'
  AND u.deleted_at IS NULL
`

type ResolveActiveAuthSubjectParams struct {
	AuthSubject string `db:"auth_subject" json:"auth_subject"`
}

func (q *Queries) ResolveActiveAuthSubject(ctx context.Context, arg ResolveActiveAuthSubjectParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, resolveActiveAuthSubject, arg.AuthSubject)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Email,
		&i.DiscordID,
		&i.AvatarUrl,
		&i.AccountState,
		&i.Timezone,
		&i.IsTest,
		&i.LeetcodePremiumOptIn,
		&i.LegacyIsAdmin,
		&i.LegacyIsGraduate,
		&i.SuspendedAt,
		&i.DeletionRequestedAt,
		&i.DeletionDueAt,
		&i.PseudonymizedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAuthLinksForUser = `-- name: RevokeAuthLinksForUser :execrows
UPDATE app.user_auth_links
SET active = false, revoked_at = $1
WHERE user_id = $2 AND active
`

type RevokeAuthLinksForUserParams struct {
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	UserID    string             `db:"user_id" json:"user_id"`
}

func (q *Queries) RevokeAuthLinksForUser(ctx context.Context, arg RevokeAuthLinksForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthLinksForUser, arg.RevokedAt, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE app.users
SET slug = $1,
    display_name = $2,
    avatar_url = $3,
    timezone = $4,
    leetcode_premium_opt_in = $5,
    revision = revision + 1
WHERE id = $6
  AND revision = $7
  AND account_state = 'active'
  AND deleted_at IS NULL
RETURNING id, slug, display_name, email, discord_id, avatar_url, account_state, timezone, is_test, leetcode_premium_opt_in, legacy_is_admin, legacy_is_graduate, suspended_at, deletion_requested_at, deletion_due_at, pseudonymized_at, deleted_at, revision, created_at, updated_at
`

type UpdateUserProfileParams struct {
	Slug                 string  `db:"slug" json:"slug"`
	DisplayName          string  `db:"display_name" json:"display_name"`
	AvatarUrl            *string `db:"avatar_url" json:"avatar_url"`
	Timezone             string  `db:"timezone" json:"timezone"`
	LeetcodePremiumOptIn bool    `db:"leetcode_premium_opt_in" json:"leetcode_premium_opt_in"`
	ID                   string  `db:"id" json:"id"`
	Revision             int64   `db:"revision" json:"revision"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Slug,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Timezone,
		arg.LeetcodePremiumOptIn,
		arg.ID,
		arg.Revision,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Email,
		&i.DiscordID,
		&i.AvatarUrl,
		&i.AccountState,
		&i.Timezone,
		&i.IsTest,
		&i.LeetcodePremiumOptIn,
		&i.LegacyIsAdmin,
		&i.LegacyIsGraduate,
		&i.SuspendedAt,
		&i.DeletionRequestedAt,
		&i.DeletionDueAt,
		&i.PseudonymizedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
