// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worker.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireLeetcodeSyncLock = `-- name: AcquireLeetcodeSyncLock :one
SELECT pg_try_advisory_xact_lock(691230184719023041::bigint) AS acquired
`

func (q *Queries) AcquireLeetcodeSyncLock(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, acquireLeetcodeSyncLock)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}

const finishLeetcodeSync = `-- name: FinishLeetcodeSync :one
UPDATE app.leetcode_sync_runs
SET finished_at = $1,
    succeeded = $2,
    fetched_count = $3,
    changed_count = $4,
    error_summary = $5
WHERE id = $6 AND finished_at IS NULL
RETURNING id, trigger_kind, requested_by_user_id, started_at, finished_at, succeeded, fetched_count, changed_count, error_summary
`

type FinishLeetcodeSyncParams struct {
	FinishedAt   pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	Succeeded    *bool              `db:"succeeded" json:"succeeded"`
	FetchedCount *int32             `db:"fetched_count" json:"fetched_count"`
	ChangedCount *int32             `db:"changed_count" json:"changed_count"`
	ErrorSummary *string            `db:"error_summary" json:"error_summary"`
	ID           string             `db:"id" json:"id"`
}

func (q *Queries) FinishLeetcodeSync(ctx context.Context, arg FinishLeetcodeSyncParams) (AppLeetcodeSyncRun, error) {
	row := q.db.QueryRow(ctx, finishLeetcodeSync,
		arg.FinishedAt,
		arg.Succeeded,
		arg.FetchedCount,
		arg.ChangedCount,
		arg.ErrorSummary,
		arg.ID,
	)
	var i AppLeetcodeSyncRun
	err := row.Scan(
		&i.ID,
		&i.TriggerKind,
		&i.RequestedByUserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Succeeded,
		&i.FetchedCount,
		&i.ChangedCount,
		&i.ErrorSummary,
	)
	return i, err
}

const getLastSuccessfulLeetcodeSync = `-- name: GetLastSuccessfulLeetcodeSync :one
SELECT id, trigger_kind, requested_by_user_id, started_at, finished_at, succeeded, fetched_count, changed_count, error_summary
FROM app.leetcode_sync_runs
WHERE succeeded
ORDER BY finished_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLastSuccessfulLeetcodeSync(ctx context.Context) (AppLeetcodeSyncRun, error) {
	row := q.db.QueryRow(ctx, getLastSuccessfulLeetcodeSync)
	var i AppLeetcodeSyncRun
	err := row.Scan(
		&i.ID,
		&i.TriggerKind,
		&i.RequestedByUserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Succeeded,
		&i.FetchedCount,
		&i.ChangedCount,
		&i.ErrorSummary,
	)
	return i, err
}

const startLeetcodeSync = `-- name: StartLeetcodeSync :one
INSERT INTO app.leetcode_sync_runs (
  id, trigger_kind, requested_by_user_id, started_at
) VALUES (
  $1, $2, $3,
  $4
)
RETURNING id, trigger_kind, requested_by_user_id, started_at, finished_at, succeeded, fetched_count, changed_count, error_summary
`

type StartLeetcodeSyncParams struct {
	ID                string             `db:"id" json:"id"`
	TriggerKind       string             `db:"trigger_kind" json:"trigger_kind"`
	RequestedByUserID *string            `db:"requested_by_user_id" json:"requested_by_user_id"`
	StartedAt         pgtype.Timestamptz `db:"started_at" json:"started_at"`
}

func (q *Queries) StartLeetcodeSync(ctx context.Context, arg StartLeetcodeSyncParams) (AppLeetcodeSyncRun, error) {
	row := q.db.QueryRow(ctx, startLeetcodeSync,
		arg.ID,
		arg.TriggerKind,
		arg.RequestedByUserID,
		arg.StartedAt,
	)
	var i AppLeetcodeSyncRun
	err := row.Scan(
		&i.ID,
		&i.TriggerKind,
		&i.RequestedByUserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Succeeded,
		&i.FetchedCount,
		&i.ChangedCount,
		&i.ErrorSummary,
	)
	return i, err
}

const upsertLeetcodeProblem = `-- name: UpsertLeetcodeProblem :one
INSERT INTO app.leetcode_problems (
  id, problem_id, leetcode_number, difficulty, is_premium
) VALUES (
  $1, $2, $3,
  $4, $5
)
ON CONFLICT (leetcode_number) DO UPDATE
SET difficulty = EXCLUDED.difficulty,
    is_premium = EXCLUDED.is_premium,
    deleted_at = NULL,
    revision = app.leetcode_problems.revision + 1
RETURNING id, problem_id, leetcode_number, difficulty, is_premium, deleted_at, revision, created_at, updated_at
`

type UpsertLeetcodeProblemParams struct {
	ID             string               `db:"id" json:"id"`
	ProblemID      string               `db:"problem_id" json:"problem_id"`
	LeetcodeNumber int32                `db:"leetcode_number" json:"leetcode_number"`
	Difficulty     AppProblemDifficulty `db:"difficulty" json:"difficulty"`
	IsPremium      bool                 `db:"is_premium" json:"is_premium"`
}

func (q *Queries) UpsertLeetcodeProblem(ctx context.Context, arg UpsertLeetcodeProblemParams) (AppLeetcodeProblem, error) {
	row := q.db.QueryRow(ctx, upsertLeetcodeProblem,
		arg.ID,
		arg.ProblemID,
		arg.LeetcodeNumber,
		arg.Difficulty,
		arg.IsPremium,
	)
	var i AppLeetcodeProblem
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.LeetcodeNumber,
		&i.Difficulty,
		&i.IsPremium,
		&i.DeletedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
