package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
)

func main() {
	generatedPath := filepath.Join("..", "generated", "api.gen.go")
	parsed, err := parser.ParseFile(token.NewFileSet(), generatedPath, nil, 0)
	if err != nil {
		panic(err)
	}
	methods := make([]string, 0)
	for _, declaration := range parsed.Decls {
		generic, ok := declaration.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range generic.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok || typeSpec.Name.Name != "StrictServerInterface" {
				continue
			}
			iface := typeSpec.Type.(*ast.InterfaceType)
			for _, field := range iface.Methods.List {
				if len(field.Names) == 1 {
					methods = append(methods, field.Names[0].Name)
				}
			}
		}
	}
	sort.Strings(methods)
	var source bytes.Buffer
	source.WriteString("// Code generated by internal/genstrict; DO NOT EDIT.\n\npackage httpapi\n\n")
	source.WriteString("import (\n\t\"context\"\n\t\"net/http\"\n\n\t\"github.com/magedmg/RSP-website/backend/internal/generated\"\n)\n\n")
	for _, method := range methods {
		fmt.Fprintf(&source, "func (strictAdapter) %s(ctx context.Context, _ generated.%sRequestObject) (generated.%sResponseObject, error) {\n\treturn strictResponse(ctx)\n}\n\n", method, method, method)
		fmt.Fprintf(&source, "func (response *strictManualResponse) Visit%sResponse(w http.ResponseWriter) error {\n\treturn response.write(w)\n}\n\n", method)
	}
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("strict_adapter.generated.go", formatted, 0o644); err != nil {
		panic(err)
	}
}
